// список анимации с описанием

[
	["AmovPercMstpSnonWnonDnon_exercisekneeBendA","Приседать"],
	["AmovPercMstpSnonWnonDnon_exercisePushup","Отжиматься"],
	["Acts_JetsMarshallingStop_loop","Сдаться"],
	["Acts_AidlPercMstpSlowWrflDnon_warmup04","Поза стоя 1"],
	["Acts_AidlPercMstpSlowWrflDnon_warmup05","Поза стоя 2"],
	["Acts_AidlPercMstpSloWWpstDnon_warmup_1","Поза стоя 3"],
	["Acts_AidlPercMstpSlowWrflDnon_warmup04","Поза стоя 4"],
	["Acts_Ambient_Relax_1","Позирование 1"],
	["Acts_Ambient_Relax_2","Позирование 2"],
	["Acts_Ambient_Relax_3","Позирование 3"],
	["Acts_Ambient_Relax_4","Позирование 4"],
	["Acts_AidlPercMstpSloWWrflDnon_warmup_7", "Поза сидя 1"],
	["Acts_AidlPercMstpSloWWpstDnon_warmup_8_loop","Поза сидя 2"],
	["Acts_Ambient_Stretching","Разминка 1"],
	["Acts_AidlPercMstpSloWWrflDnon_warmup_3_loop","Разминка 2"],
	["Acts_AidlPercMstpSloWWrflDnon_warmup_7_loop","Разминка 3"],
	["Acts_Briefing_SA_Loop","Часовой 1"],
	["Acts_GetAttention_Loop","Часовой 2"],
	["Acts_Soldier_Moves_Inside_1","Часовой 3"],
	["UnaErcPoslechVelitele1","Руки связаны стоя"],
	["Acts_AidlPsitMstpSsurWnonDnon01", "Руки связаны сидя"],
	["Acts_A_M01_briefing","Руки на пояс"],
	["Acts_AidlPercMstpSloWWrflDnon_warmup_8","Закрытая поза"],
	["Acts_Ambient_Defensive","Показать стоп"],
	["Acts_Ambient_Approximate","Развести руками"],
	["Acts_Ambient_Disagreeing","Нет/отказано"],
	["Acts_JetsShooterNavigate_loop", "Махать руками"],
	["Acts_JetsCrewaidFCrouch_loop_m","Сидеть на колене"],
	["Acts_AidlPercMstpSnonWnonDnon_warmup_4_loop","Поза гоп-стоп"],
	["Acts_Ambient_Gestures_Yawn","Зевок"],
	["Acts_JetsFlyoverCheering_1","Пролет самолета"],
	["AmovPercMstpSnonWnonDnon_exerciseKata","Кунфу разминка"],
	["Acts_JetsMarshallingClear_loop","Поднять правую руку"],
	["Acts_JetsMarshallingEmergencyStop_loop","Перекрестить руки сверху"],
	["Acts_EpicSplit", "Сесть на шпагат"],
	["InBaseMoves_SittingRifle2","Сидеть на стуле 1"],
	["HubSittingChairA_idle2","Сидеть на стуле 2"],
	["Acts_Dance_01","Танец 1"],
	["Acts_Dance_02","Танец 2"],
	["Acts_carFixingWheel","Чинить колесо "],
	["Acts_CivilHiding_2","Контуженный"],
	["Acts_CivilShocked_2","Шокирован"]
];