_uniform = [
	// ======================================================================
	// Vanilla
	// ======================================================================
		// "All" ============================================================
			"U_B_CBRN_Suit_01_Tropic_F"			,
			"U_B_CBRN_Suit_01_Wdl_F"			,
			"U_I_CBRN_Suit_01_AAF_F"			,
			"U_I_E_CBRN_Suit_01_EAF_F"			,
			"U_I_Wetsuit"						,
			"U_O_Wetsuit"						,
		// "Infantry" =======================================================
			"U_I_CombatUniform_shortsleeve"		,
			"U_I_CombatUniform"					,
			"U_O_CombatUniform_ocamo"           ,
			"U_B_CombatUniform_mcam_wdl_f"		,
			"U_B_CombatUniform_vest_mcam_wdl_f"	,
			"U_B_CTRG_Soldier_3_F"				,
			"U_B_CTRG_Soldier_F"				,
			"U_B_CTRG_Soldier_urb_1_F"			,
			"U_B_CTRG_Soldier_urb_3_F"			,
			"U_B_T_Soldier_F"					,
			"U_B_T_Soldier_SL_F"				,
			"U_O_T_Soldier_F"					,
			"U_I_E_Uniform_01_F"				,
			"U_I_E_Uniform_01_shortsleeve_F"	,
			"U_I_E_Uniform_01_sweater_F"		,
			"U_O_officer_noInsignia_hex_F"		,
			"U_O_R_Gorka_01_black_F"			,
			"U_O_R_Gorka_01_brown_F"			,
			"U_O_R_Gorka_01_camo_F"				,
			"U_O_R_Gorka_01_F"					,
			"U_O_SpecopsUniform_ocamo"			,
	// ======================================================================
	// SSU
	// ======================================================================
		// Special Purpose ========================================
			"U_SSU_Special_Purpose_Suit_AOR2"				,
			"U_SSU_Special_Purpose_Suit_AOR2_b"				,
			"U_SSU_Special_Purpose_Suit_Black"				,
			"U_SSU_Special_Purpose_Suit_Black_b"			,
			"U_SSU_Special_Purpose_Suit_M81"				,
			"U_SSU_Special_Purpose_Suit_M81_b"				,
			"U_SSU_Special_Purpose_Suit_MCAM_Black"			,
			"U_SSU_Special_Purpose_Suit_MCAM_Black_b"		,
			"U_SSU_Special_Purpose_Suit_MCAM_Tropic"		,
			"U_SSU_Special_Purpose_Suit_MCAM_Tropic_b"		,
			"U_SSU_Special_Purpose_Suit_MCAM_Woodland"		,
			"U_SSU_Special_Purpose_Suit_MCAM_Woodland_b"	,
		// Stealth Uniform ========================================
			"U_SSU_Stealth_Uniform_AOR2"					,
			"U_SSU_Stealth_Uniform_Black"					,
			"U_SSU_Stealth_Uniform_M81"						,
			"U_SSU_Stealth_Uniform_MCAM_Black"				,
			"U_SSU_Stealth_Uniform_MCAM_Tropic"				,
			"U_SSU_Stealth_Uniform_MCAM_Woodland"			,
			"U_SSU_Stealth_Uniform_Rolled_AOR2"				,
			"U_SSU_Stealth_Uniform_Rolled_Black"			,
			"U_SSU_Stealth_Uniform_Rolled_M81"				,
			"U_SSU_Stealth_Uniform_Rolled_MCAM_Black"		,
			"U_SSU_Stealth_Uniform_Rolled_MCAM_Tropic"		,
			"U_SSU_Stealth_Uniform_Rolled_MCAM_Woodland"	,
			"U_SSU_Stealth_Uniform_Sleeved_AOR2"			,
			"U_SSU_Stealth_Uniform_Sleeved_Black"			,
			"U_SSU_Stealth_Uniform_Sleeved_M81"				,
			"U_SSU_Stealth_Uniform_Sleeved_MCAM_Black"		,
			"U_SSU_Stealth_Uniform_Sleeved_MCAM_Tropic"		,
			"U_SSU_Stealth_Uniform_Sleeved_MCAM_Woodland"	,
	// ======================================================================
	// AGE
	// ======================================================================
		// "Infantry" =============================================
			"AGE_CryeG3_ATACSFG"				,
			"AGE_CryeG3_BlackMCam"				,
			"AGE_CryeG3_G_BlackMCam"			,
			"AGE_CryeG3_AOR1"					,
			"AGE_CryeG3_G_AOR1"					,
			"AGE_CryeG3_Black"					,
			"AGE_CryeG3_BrownATACSFG"			,
			"AGE_CryeG3_G_ATACSFG"				,
			"AGE_CryeG3_G_Black"				,
			"AGE_CryeG3_G_BrownATACSFG"			,
			"AGE_CryeG3_G_Olive"				,
			"AGE_CryeG3_G_OliveATACSFG"			,
			"AGE_CryeG3_G_OliveBlack"			,
			"AGE_CryeG3_Olive"					,
			"AGE_CryeG3_OliveATACSFG"			,
			"AGE_CryeG3_OliveBlack"				,
			"AGE_Fatigues_ATACSFG"				,
			"AGE_Fatigues_ATACSFG_Gloves"		,
			"AGE_Fatigues_Black"				,
			"AGE_Fatigues_Black_Gloves"			,
			"AGE_Fatigues_BrownATACSFG"			,
			"AGE_Fatigues_BrownATACSFG_Gloves"	,
			"AGE_Fatigues_BrownCamo"			,
			"AGE_Fatigues_BrownGreen"			,
			"AGE_Fatigues_CamoBrown"			,
			"AGE_Fatigues_CamoGreen"			,
			"AGE_Fatigues_CamoGreen2"			,
			"AGE_Fatigues_CamoGrey"				,
			"AGE_Fatigues_GreenBrown"			,
			"AGE_Fatigues_GreyGreen"			,
			"AGE_Fatigues_Short_ATACSFG"		,
			"AGE_Fatigues_Short_Black"			,
			"AGE_Fatigues_Short_BrownATACSFG"	,
			"AGE_Fatigues_Short_TaigaD"			,
			"AGE_Fatigues_Short_TaigaW"			,
			"AGE_Fatigues_TaigaD"				,
			"AGE_Fatigues_TaigaD_Gloves"		,
			"AGE_Fatigues_TaigaW"				,
			"AGE_Fatigues_TaigaW_Gloves"		,
			"AGE_G3_Uniform_ATACSFG"			,
			"AGE_G3_Uniform_Short_ATACSFG"		,
			"AGE_Gorka_AtacsFG"					,
			"AGE_Gorka_Grey"					,
			"AGE_Gorka_Sand"					,
			"AGE_VKBO_Flora"					,
			"AGE_VKBO_Summer"					,
			"AGE_Voin_AtacsFG"					,
			"AGE_Voin_AtacsFG_G"				,
			"AGE_Voin_Grey"						,
			"AGE_Voin_Grey_G"					,
	// ======================================================================
	// AEW
	// ======================================================================
		// "Infantry" ===========================================
			"GUR_fat_black_1"									,
			"GUR_fat_black_2"									,
			"GUR_unf_black"										,
			"NAA_fat_CBRN_1"									,
			"HEL_fat_CBRN_1"									,
			"NAA_fat_alpat_ard1"								,
			"NAA_fat_alpat_tac_ard1"							,
			"NAA_fat_alpat_rs_ard1"								,
			"HEL_fat_1"											,
			"HEL_fat_2"											,
			"ASF_uniform_blk"									,
			"NAA_fat_alpat_wdl1"								,
			"NAA_fat_alpat_tac_wdl1"							,
			"NAA_fat_alpat_rs_tac_wld1"							,
			"NAA_fat_alpat_rs_wdl1"								,	
			"MYR_fat_7"											,
			"MYR_fat_5"											,
			"MYR_fat_6"											,
			"MYR_fat_8"											,
			"MYR_fat_9"											,
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP ACR ==================================================
			"CUP_U_B_CZ_DST_NoKneepads",
			"CUP_U_B_CZ_WDL_TShirt"								,		
			"CUP_U_B_CZ_WDL_Kneepads"							,
			"CUP_U_B_CZ_DST_TShirt"								,
			"CUP_U_B_CZ_DST_Kneepads_Sleeve",
			"CUP_U_B_CZ_WDL_NoKneepads",
			"CUP_U_B_CZ_WDL_Kneepads_Gloves",
		// CUP BAF ==================================================
            "CUP_U_B_BAF_MTP_UBACSLONG_Gloves",
            "CUP_U_B_BAF_MTP_UBACSLONG",
            "CUP_U_B_BAF_MTP_UBACSROLLED_Gloves",
            "CUP_U_B_BAF_MTP_UBACSTSHIRT",
			"CUP_U_B_BAF_MTP_UBACSTSHIRT_Gloves",
			"CUP_U_B_BAF_DDPM_UBACSTSHIRT_Gloves",
			"CUP_U_B_BAF_DPM_UBACSLONG",
		// CUP BDU ==================================================
			"CUP_U_B_BDUv2_Alpenflage",
			"CUP_U_B_BDUv2_gloves_Alpenflage",
			"CUP_U_B_BDUv2_roll_Alpenflage",
			"CUP_U_B_BDUv2_roll_gloves_Alpenflage",
			"CUP_U_B_BDUv2_CEU",
			"CUP_U_B_BDUv2_gloves_CEU",
			"CUP_U_B_BDUv2_roll_CEU",
			"CUP_U_B_BDUv2_roll_gloves_CEU",
			"CUP_U_B_BDUv2_DCU",
			"CUP_U_B_BDUv2_gloves_DCU",
			"CUP_U_B_BDUv2_roll_DCU",
			"CUP_U_B_BDUv2_roll_gloves_DCU",
			"CUP_U_B_BDUv2_DDPM",
			"CUP_U_B_BDUv2_gloves_DDPM",
			"CUP_U_B_BDUv2_roll_DDPM",
			"CUP_U_B_BDUv2_roll_gloves_DDPM",
			"CUP_U_B_BDUv2_desert",
			"CUP_U_B_BDUv2_gloves_desert",
			"CUP_U_B_BDUv2_roll_desert",
			"CUP_U_B_BDUv2_roll_gloves_desert",
			"CUP_U_B_BDUv2_DPM",
			"CUP_U_B_BDUv2_gloves_DPM",
			"CUP_U_B_BDUv2_roll_DPM",
			"CUP_U_B_BDUv2_roll_gloves_DPM",
			"CUP_U_B_BDUv2_ERDL_highland",
			"CUP_U_B_BDUv2_gloves_ERDL_highland",
			"CUP_U_B_BDUv2_roll_ERDL_highland",
			"CUP_U_B_BDUv2_roll_gloves_ERDL_highland",
			"CUP_U_B_BDUv2_ERDL_lowland",
			"CUP_U_B_BDUv2_gloves_ERDL_lowland",
			"CUP_U_B_BDUv2_roll_ERDL_lowland",
			"CUP_U_B_BDUv2_roll_gloves_ERDL_lowland",
			"CUP_U_B_BDUv2_M81",
			"CUP_U_B_BDUv2_gloves_M81",
			"CUP_U_B_BDUv2_roll_M81",
			"CUP_U_B_BDUv2_roll_gloves_M81",
			"CUP_U_B_BDUv2_OD",
			"CUP_U_B_BDUv2_gloves_OD",
			"CUP_U_B_BDUv2_roll_OD",
			"CUP_U_B_BDUv2_roll_gloves_OD",
			"CUP_U_B_BDUv2_Tpattern",
			"CUP_U_B_BDUv2_gloves_Tpattern",
			"CUP_U_B_BDUv2_roll_Tpattern",
			"CUP_U_B_BDUv2_roll_gloves_Tpattern",
			"CUP_U_B_BDUv2_Tigerstripe",
			"CUP_U_B_BDUv2_gloves_Tigerstripe",
			"CUP_U_B_BDUv2_roll_Tigerstripe",
			"CUP_U_B_BDUv2_roll_gloves_Tigerstripe",
			"CUP_U_B_BDUv2_Urban",
			"CUP_U_B_BDUv2_gloves_Urban",
			"CUP_U_B_BDUv2_roll_Urban",
			"CUP_U_B_BDUv2_roll_gloves_Urban",
		// CUP CDF ==================================================
			"CUP_U_B_CDF_DST_1",
			"CUP_U_B_CDF_DST_2",
			"CUP_U_B_CDF_FST_1",
			"CUP_U_B_CDF_FST_2",
			"CUP_U_B_CDF_MNT_1",
			"CUP_U_B_CDF_MNT_2",
			"CUP_U_B_CDF_SNW_1",
			"CUP_U_B_CDF_SNW_2",
		// CUP ChDKZ ==================================================
			"CUP_U_O_CHDKZ_Kam_02",
			"CUP_U_O_CHDKZ_Commander",
			"CUP_U_O_CHDKZ_Kam_06",
		// CUP Crye ==================================================
			"CUP_U_CRYE_ATACSAU_Full",
			"CUP_U_CRYE_ATACSAU_Roll",
			"CUP_U_CRYE_ATACSFG_Full",
			"CUP_U_CRYE_ATACSFG_Roll",
			"CUP_U_CRYE_BLK_Full",
			"CUP_U_CRYE_BLK_Roll",
			"CUP_U_CRYE_BLK_RUS_Full",
			"CUP_U_CRYE_BLK_RUS_Roll",
			"CUP_U_CRYE_G3C_AOR1",
			"CUP_U_CRYE_G3C_AOR2",
			"CUP_U_CRYE_G3C_ATACSAU",
			"CUP_U_CRYE_G3C_ATACSFG",
			"CUP_U_CRYE_G3C_BLK",
			"CUP_U_CRYE_G3C_M81",
			"CUP_U_CRYE_G3C_RGR",
			"CUP_U_CRYE_RGR_Full",
			"CUP_U_CRYE_RGR_Roll",
			"CUP_U_CRYE_TAN_Full",
			"CUP_U_CRYE_TAN_Roll",
		// CUP GER ==================================================
			"CUP_U_B_GER_Fleck_Crye",
			"CUP_U_B_GER_Fleck_Crye2",
			"CUP_U_B_GER_Crye",
			"CUP_U_B_GER_Crye2",
			"CUP_U_B_GER_Flecktarn_5",
			"CUP_U_B_GER_Flecktarn_6",
			"CUP_U_B_GER_Flecktarn_7",
			"CUP_U_B_GER_Flecktarn_8",
			"CUP_U_B_GER_Tropentarn_5",
			"CUP_U_B_GER_Tropentarn_6",
			"CUP_U_B_GER_Tropentarn_7",
			"CUP_U_B_GER_Tropentarn_8",
		// CUP HIL ACU ==================================================
			"CUP_U_B_HIL_ACU_CCE",
			"CUP_U_B_HIL_ACU_Gloves_CCE",
			"CUP_U_B_HIL_ACU_TTS",
			"CUP_U_B_HIL_ACU_Gloves_TTS",
		// CUP Partisan ==================================================
			"CUP_U_O_Partisan_TTsKO",
		// CUP SLA ==================================================
			"CUP_U_O_SLA_MixedCamo",
			"CUP_U_O_SLA_Desert",
			"CUP_U_O_SLA_Green",
			"CUP_U_O_SLA_Urban",
		// CUP Takistani ==================================================
			"CUP_U_O_TK_Green",
		// CUP USMC ==================================================
			"CUP_U_B_USMC_MCCUU_M81",
			"CUP_U_B_USMC_MCCUU_M81_gloves",
			"CUP_U_B_USMC_MCCUU_M81_roll",
			"CUP_U_B_USMC_MCCUU_M81_roll_gloves",
			"CUP_U_B_USMC_FROG3_WMARPAT",
			"CUP_U_B_USMC_FROG3_DMARPAT",
			"CUP_U_B_USMC_MCCUU",
			"CUP_U_B_USMC_MCCUU_gloves",
			"CUP_U_B_USMC_MCCUU_roll",
			"CUP_U_B_USMC_MCCUU_roll_gloves",
			"CUP_U_B_USMC_MCCUU_des",
			"CUP_U_B_USMC_MCCUU_des_gloves",
			"CUP_U_B_USMC_MCCUU_des_roll",
			"CUP_U_B_USMC_MCCUU_des_roll_gloves",
		// CUP RUS ==================================================
			"CUP_U_O_RUS_BeigeDigital_MSV",
			"CUP_U_O_RUS_BeigeDigital_MSV_rolled_up",
			"CUP_U_O_RUS_VSR93_MSV",
			"CUP_U_O_RUS_VSR93_MSV_rolled_up",
			"CUP_U_O_RUS_VSR98_MSV",
			"CUP_U_O_RUS_VSR98_MSV_rolled_up",
			"CUP_U_O_RUS_EMR_1",
			"CUP_U_O_RUS_EMR_2",
			"CUP_U_O_RUS_Flora_1",
			"CUP_U_O_RUS_Flora_2",
			"CUP_U_O_RUS_BeigeDigital_VDV",
			"CUP_U_O_RUS_BeigeDigital_VDV_rolled_up",
			"CUP_U_O_RUS_VSR93_VDV",
			"CUP_U_O_RUS_VSR93_VDV_rolled_up",
			"CUP_U_O_RUS_VSR93_VDV_rolled_up_gloves2",
			"CUP_U_O_RUS_VSR98_VDV",
			"CUP_U_O_RUS_VSR98_VDV_rolled_up",
			"CUP_U_O_RUS_VSR98_VDV_rolled_up_gloves2",
			"CUP_U_O_RUS_EMR_1_VDV",
			"CUP_U_O_RUS_EMR_2_VDV",
			"CUP_U_O_RUS_KSOR_VDV",
			"CUP_U_O_RUS_KSOR_VDV_rolled_up",
			"CUP_U_O_RUS_Flora_1_VDV",
			"CUP_U_O_RUS_Flora_2_VDV",
			"CUP_U_O_RUS_Flora_3",
			"CUP_U_O_RUS_M88_MSV",
			"CUP_U_O_RUS_M88_MSV_rolled_up",
			"CUP_U_O_RUS_M88_VDV",
			"CUP_U_O_RUS_M88_VDV_rolled_up",
		// CUP RUS GORKA ==================================================
			"CUP_U_O_RUS_Gorka_Green",
			"CUP_U_O_RUS_Gorka_Green_gloves2",
			"CUP_U_O_RUS_Gorka_Partizan",
			"CUP_U_O_RUS_Gorka_Partizan_gloves2",
			"CUP_U_O_RUS_Gorka_Partizan_A",
			"CUP_U_O_RUS_Gorka_Partizan_A_gloves2",
		// CUP ODKB ==================================================
			"CUP_U_O_ODKB_KSOR_VDV",
			"CUP_U_O_ODKB_KSOR_VDV_rolled_up"
];

_vest = [
	// ======================================================================
	// Vanilla
	// ======================================================================
		// "0" ==================================================
			"V_BandollierB_blk"									,
			"V_BandollierB_ghex_F"								,
			"V_BandollierB_oli"									,
			"V_BandollierB_rgr"									,
			"V_Chestrig_blk"									,
			"V_Chestrig_oli"									,
			"V_Chestrig_rgr"									,
			"V_HarnessO_brn"									,
			"V_HarnessO_ghex_F"									,
			"V_LegStrapBag_black_F"								,
			"V_LegStrapBag_olive_F"								,
			"V_Rangemaster_belt"								,
			"V_RebreatherIA"									,
			"V_RebreatherIR"									,
			"V_SmershVest_01_F"									,
			"V_SmershVest_01_radio_F"							,
			"V_TacChestrig_grn_F"								,
			"V_TacChestrig_oli_F"								,
		// "1" ==================================================
			"V_I_G_resistanceLeader_F"							,
			"V_TacVest_khk"                                     ,
			"V_TacVest_blk"										,
			"V_TacVest_camo"									,
			"V_TacVest_oli"										,
			"V_TacVestIR_blk"									,
		// "3" ==================================================
			"V_PlateCarrierL_CTRG"								,
		    "V_PlateCarrierH_CTRG"								,
			"V_CarrierRigKBT_01_EAF_F"							,
			"V_CarrierRigKBT_01_light_EAF_F"					,
			"V_CarrierRigKBT_01_light_Olive_F"					,
			"V_CarrierRigKBT_01_Olive_F"						,
			"V_PlateCarrier1_blk"								,
			"V_PlateCarrier1_rgr_noflag_F"						,
			"V_PlateCarrierIAGL_dgtl"							,
			"V_PlateCarrierIA1_dgtl"							,
			"V_PlateCarrierIA2_dgtl"							,
		// "3+" =================================================
			"V_CarrierRigKBT_01_heavy_EAF_F"					,
			"V_CarrierRigKBT_01_heavy_Olive_F"					,
		// "4" ==================================================
			"V_PlateCarrier1_blk"								,
			"V_PlateCarrier2_blk"								,
			"V_PlateCarrier2_rgr_noflag_F"						,
	// ======================================================================
	// SSU
	// ======================================================================
		// "0" ==================================================
			"V_SSU_Tactical_Chest_Rig_Black"					,
			"V_SSU_Tactical_Chest_Rig_Green"					,
		// "2" ==================================================
			"V_SSU_Tactical_Vest_AOR2"							,
			"V_SSU_Tactical_Vest_MCAM_Black"					,
			"V_SSU_Tactical_Vest_Black"							,
			"V_SSU_Tactical_Vest_M81"							,
			"V_SSU_Tactical_Vest_MCAM_Tropic"					,
			"V_SSU_Tactical_Vest_MCAM_Woodland"					,
		// "3" ==================================================
			"V_SSU_Carrier_Lite_AOR2"							,
			"V_SSU_Carrier_Lite_MCAM_Black"						,
			"V_SSU_Carrier_Lite_Black"							,
			"V_SSU_Carrier_Lite_M81"							,
			"V_SSU_Carrier_Lite_MCAM_Tropic"					,
			"V_SSU_Carrier_Lite_MCAM_Woodland"					,
			"V_SSU_Modular_Carrier_Lite_AOR2"					,
			"V_SSU_Modular_Carrier_Lite_MCAM_Black"				,
			"V_SSU_Modular_Carrier_Lite_Black"					,
			"V_SSU_Modular_Carrier_Lite_M81"					,
			"V_SSU_Modular_Carrier_Lite_MCAM_Tropic"			,
			"V_SSU_Modular_Carrier_Lite_MCAM_Woodland"			,
		// "4" ==================================================
			"V_SSU_Carrier_Rig_AOR2"							,
			"V_SSU_Carrier_Rig_MCAM_Black"						,
			"V_SSU_Carrier_Rig_Black"							,
			"V_SSU_Carrier_Rig_M81"								,
			"V_SSU_Carrier_Rig_MCAM_Tropic"						,
			"V_SSU_Carrier_Rig_MCAM_Woodland"					,
		// "5" ==================================================
			"V_SSU_Carrier_Special_Rig_AOR2"					,
			"V_SSU_Carrier_Special_Rig_MCAM_Black"				,
			"V_SSU_Carrier_Special_Rig_Black"					,
			"V_SSU_Carrier_Special_Rig_M81"						,
			"V_SSU_Carrier_Special_Rig_MCAM_Tropic"				,
			"V_SSU_Carrier_Special_Rig_MCAM_Woodland"			,
	// ======================================================================
	// AGE
	// ======================================================================
		// "2" ==================================================
			"AGE_LV119_AK_Black"								,
			"AGE_LV119_AK_AOR1"									,
			"AGE_LV119_AK_Holster_AOR1"							,
			"AGE_LV119_AK_Black_Unmarked"						,
			"AGE_LV119_AK_Holster_Black"						,
			"AGE_LV119_AK_Holster_Black_Unmarked"				,
			"AGE_LV119_AK_Holster_TaigaD"						,
			"AGE_LV119_AK_Holster_TaigaW"						,
			"AGE_LV119_AK_TaigaD"								,
			"AGE_LV119_AK_TaigaW"								,
			"AGE_LV119_Pouches_AOR1"							,
			"AGE_LV119_Pouches_Black"							,
			"AGE_LV119_Pouches_Black_Unmarked"					,
			"AGE_LV119_Pouches_TaigaD"							,
			"AGE_LV119_Pouches_TaigaW"							,
			"AGE_LV119_SL_AOR1"									,
			"AGE_LV119_SL_Holster_AOR1"							,
			"AGE_LV119_SL_Black"								,
			"AGE_LV119_SL_Black_Unmarked"						,
			"AGE_LV119_SL_Holster_Black"						,
			"AGE_LV119_SL_Holster_Black_Unmarked"				,
			"AGE_LV119_SL_Holster_TaigaD"						,
			"AGE_LV119_SL_Holster_TaigaW"						,
			"AGE_LV119_SL_TaigaD"								,
			"AGE_LV119_SL_TaigaW"								,
			"AGE_LV119_SMG_Black"								,
			"AGE_LV119_SMG_Black_Unmarked"						,
			"AGE_LV119_SMG_TaigaD"								,
			"AGE_LV119_SMG_TaigaW"								,
			"AGE_TV110_AK_Coyote"								,
			"AGE_TV110_AK_Holster_Coyote"						,
			"AGE_TV110_AK_Black"								,
			"AGE_TV110_AK_Flora"								,
			"AGE_TV110_AK_Flora_Holster"						,
			"AGE_TV110_AK_Flora_Holster_2"						,
			"AGE_TV110_AK_Holster_Black"						,
			"AGE_TV110_SMG_Black"								,
			"AGE_TV110_SMG_Holster_Black"						,
			"AGE_WAS_AK_AtacsFG"								,
			"AGE_WAS_AK_Black"									,
			"AGE_WAS_AK_Holster_AtacsFG"						,
			"AGE_WAS_AK_Holster_Black"							,
			"AGE_WAS_AK_Holster_Olive"							,
			"AGE_WAS_AK_Olive"									,
			"AGE_WAS_Heavy_AK_AtacsFG"							,
			"AGE_WAS_Heavy_AK_Black"							,
			"AGE_WAS_Heavy_AK_Holster_AtacsFG"					,
			"AGE_WAS_Heavy_AK_Holster_Black"					,
			"AGE_WAS_Heavy_AK_Holster_Olive"					,
			"AGE_WAS_Heavy_AK_HolsterV2_AtacsFG"				,
			"AGE_WAS_Heavy_AK_HolsterV2_Black"					,
			"AGE_WAS_Heavy_AK_HolsterV2_Olive"					,
			"AGE_WAS_Heavy_AK_Olive"							,
			"AGE_WAS_Light_AK_AtacsFG"							,
			"AGE_WAS_Light_AK_Black"							,
			"AGE_WAS_Light_AK_Holster_AtacsFG"					,
			"AGE_WAS_Light_AK_Holster_Black"					,
			"AGE_WAS_Light_AK_Holster_Olive"					,
			"AGE_WAS_Light_AK_Olive"							,
			"AGE_WAS_LightV2_AK_Holster_AtacsFG"				,
			"AGE_WAS_LightV2_AK_Holster_Black"					,
			"AGE_WAS_LightV2_AK_Holster_Olive"					,
			"AGE_WAS_Medium_AK_AtacsFG"							,
			"AGE_WAS_Medium_AK_Black"							,
			"AGE_WAS_Medium_AK_Holster_AtacsFG"					,
			"AGE_WAS_Medium_AK_Holster_Black"					,
			"AGE_WAS_Medium_AK_Holster_Olive"					,
			"AGE_WAS_Medium_AK_Olive"							,
			"AGE_WAS_Special_Holster_AtacsFG"					,
			"AGE_WAS_Special_Holster_Black"						,
			"AGE_WAS_Special_Holster_Olive"						,
		// "3" ==================================================
			"AGE_Aspis_AK_Belt_Black"							,
			"AGE_Aspis_AK_Belt_Olive"							,
			"AGE_Aspis_AK_Black"								,
			"AGE_Aspis_AK_Olive"								,
			"AGE_Aspis_AK_Rig_Black"							,
			"AGE_Aspis_AK_Rig_Olive"							,
			"AGE_Aspis_Belt_Black"								,
			"AGE_Aspis_Belt_Olive"								,
			"AGE_Aspis_Black"									,
			"AGE_Aspis_Holster_Black"							,
			"AGE_Aspis_Holster_Olive"							,
			"AGE_Aspis_Olive"									,
			"AGE_Aspis_Rig_Black"								,
			"AGE_Aspis_Rig_Olive"								,
			"AGE_Aspis_SMG_Belt_Black"							,
			"AGE_Aspis_SMG_Belt_Olive"							,
			"AGE_Aspis_SMG_Black"								,
			"AGE_Aspis_SMG_Olive"								,
	// ======================================================================
	// AEW
	// ======================================================================
		// "0" ==================================================
			"NAA_vest_Chestrig_ALPAT_1"							,
			"CSAT_NA_vest_LVB_des_hex"							,
		// "1" ==================================================
			"NAA_vest_Tac_MP_ALPAT"								,
			"CSAT_NA_vest_tac_des_hex_F"						,
		// "1+" =================================================
			"CSAT_NA_vest_raven_F"								,
		// "3" ==================================================
			"NAA_vest_nato_alpat_ard1"							,
			"HEL_vest_greece_1"									,
			"NAA_vest_nato_alpat_MP1"							,
			"NAA_vst_GA_lite_alpat_ard1"						,
			"MYR_vest_GA_lite_blk"								,
			"WAM_vest_GA_lite_CAcamo"							,
			"HEL_vest_greece_3"									,
			"NAA_vst_GA_rig_alpat_ard1"							,
			"MYR_vest_GA_rig_blk"								,
			"WAM_vest_GA_rig_CAcamo"							,
			"HEL_vest_greece_5"									,
			"AEW_vest_Robin_F"									,
		// "4" ==================================================
			"NAA_vest_nato_alpat_ard2"							,
			"HEL_vest_greece_2"									,
			"NAA_vest_nato_alpat_MP2"							,
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP ACR ==================================================
			"CUP_V_CZ_vest01",
			"CUP_V_CZ_vest02",
			"CUP_V_CZ_vest07",
			"CUP_V_CZ_vest08",
			"CUP_V_CZ_vest11",
			"CUP_V_CZ_vest12",
			"CUP_V_CZ_vest15",
			"CUP_V_CZ_vest16",
			"CUP_V_CZ_NPP2006_nk_black",
			"CUP_V_CZ_NPP2006_nk_des",
			"CUP_V_CZ_NPP2006_nk_vz95",
			"CUP_V_CZ_NPP2006_light_vz95",
		// CUP BAF ==================================================
			"CUP_V_B_BAF_DDPM_Osprey_Mk3_Empty",
			"CUP_V_B_BAF_DPM_Osprey_Mk3_Empty",
			"CUP_V_B_BAF_DDPM_Osprey_Mk3_AutomaticRifleman",
			"CUP_V_B_BAF_DDPM_Osprey_Mk3_Engineer",
			"CUP_V_B_BAF_DDPM_Osprey_Mk3_Grenadier",
			"CUP_V_B_BAF_DPM_Osprey_Mk3_Grenadier",
			"CUP_V_B_BAF_DDPM_Osprey_Mk3_Medic",
			"CUP_V_B_BAF_DPM_Osprey_Mk3_Medic",
			"CUP_V_B_BAF_DDPM_Osprey_Mk3_Officer",
			"CUP_V_B_BAF_DPM_Osprey_Mk3_Officer",
			"CUP_V_B_BAF_DDPM_Osprey_Mk3_Rifleman",
			"CUP_V_B_BAF_DPM_Osprey_Mk3_Rifleman",
			"CUP_V_B_BAF_MTP_Osprey_Mk4_AutomaticRifleman",
			"CUP_V_B_BAF_MTP_Osprey_Mk4_Engineer",
			"CUP_V_B_BAF_MTP_Osprey_Mk4_Grenadier",
			"CUP_V_B_BAF_MTP_Osprey_Mk4_Officer",
			"CUP_V_B_BAF_MTP_Osprey_Mk4_Scout",
			"CUP_V_B_BAF_MTP_Osprey_Mk4_Rifleman",
		// CUP SLA ==================================================
			"CUP_V_O_SLA_6B3_1_DES",
			"CUP_V_O_SLA_6B3_1_URB",
			"CUP_V_O_SLA_6B3_1_WDL",
			"CUP_V_O_SLA_Flak_Vest01",
			"CUP_V_O_SLA_Flak_Vest02",
			"CUP_V_O_SLA_Flak_Vest03",
			"CUP_V_O_SLA_6B3_5_DES",
			"CUP_V_O_SLA_6B3_5_URB",
			"CUP_V_O_SLA_6B3_5_WDL",
			"CUP_V_O_SLA_6B3_2_DES",
			"CUP_V_O_SLA_6B3_2_URB",
			"CUP_V_O_SLA_6B3_2_WDL",
			"CUP_V_O_SLA_6B3_3_DES",
			"CUP_V_O_SLA_6B3_3_URB",
			"CUP_V_O_SLA_6B3_3_WDL",
			"CUP_V_O_SLA_M23_1_BRN",
			"CUP_V_O_SLA_M23_1_OD",
			"CUP_V_O_SLA_Carrier_Belt",
			"CUP_V_O_SLA_Carrier_Belt02",
		// CUP RUS ==================================================
			"CUP_V_RUS_6B3_1",
			"CUP_V_RUS_6B3_3",
			"CUP_V_RUS_6B3_4",
			"CUP_V_RUS_6B3_Flora_1",
			"CUP_V_RUS_6B3_Flora_3",
			"CUP_V_RUS_6B3_Flora_4",
			"CUP_V_RUS_6B45_1_BeigeDigital",
			"CUP_V_RUS_6B45_2_BeigeDigital",
			"CUP_V_RUS_6B45_3_BeigeDigital",
			"CUP_V_RUS_6B45_4_BeigeDigital",
			"CUP_V_RUS_6B45_1",
			"CUP_V_RUS_6B45_2",
			"CUP_V_RUS_6B45_3",
			"CUP_V_RUS_6B45_4",
			"CUP_Vest_RUS_6B45_Sh117_BeigeDigital",
			"CUP_Vest_RUS_6B45_Sh117_PKP_BeigeDigital",
			"CUP_Vest_RUS_6B45_Sh117",
			"CUP_Vest_RUS_6B45_Sh117_PKP",
			"CUP_V_RUS_Smersh_1",
			"CUP_V_RUS_Smersh_2",
		// CUP CDF ==================================================
			"CUP_V_CDF_6B3_1_Green",
			"CUP_V_CDF_6B3_2_Green",
			"CUP_V_CDF_6B3_1_DST",
			"CUP_V_CDF_6B3_2_DST",
			"CUP_V_CDF_6B3_1_FST",
			"CUP_V_CDF_6B3_2_FST",
			"CUP_V_CDF_6B3_1_MNT",
			"CUP_V_CDF_6B3_2_MNT",
			"CUP_V_CDF_6B3_1_SNW",
			"CUP_V_CDF_6B3_2_SNW",
			"CUP_V_CDF_6B3_5_Green",
			"CUP_V_CDF_6B3_5_DST",
			"CUP_V_CDF_6B3_5_FST",
			"CUP_V_CDF_6B3_5_MNT",
			"CUP_V_CDF_6B3_5_SNW",
			"CUP_V_CDF_6B3_3_Green",
			"CUP_V_CDF_6B3_3_DST",
			"CUP_V_CDF_6B3_3_FST",
			"CUP_V_CDF_6B3_3_MNT",
			"CUP_V_CDF_6B3_3_SNW",
		// CUP ChDKZ ==================================================
			"CUP_V_O_Ins_Carrier_Rig",
			"CUP_V_O_Ins_Carrier_Rig_Com",
			"CUP_V_O_Ins_Carrier_Rig_Light",
			"CUP_V_O_Ins_Carrier_Rig_MG",
		// CUP CIRAS ==================================================
			"CUP_V_B_Ciras_Black3",
			"CUP_V_B_Ciras_Black4",
			"CUP_V_B_Ciras_Coyote3",
			"CUP_V_B_Ciras_Coyote4",
			"CUP_V_B_Ciras_Khaki3",
			"CUP_V_B_Ciras_Khaki4",
			"CUP_V_B_Ciras_Olive3",
			"CUP_V_B_Ciras_Olive4",
			"CUP_V_PMC_CIRAS_OD_Empty",
			"CUP_V_PMC_CIRAS_Black_Empty",
			"CUP_V_PMC_CIRAS_Coyote_Empty",
			"CUP_V_PMC_CIRAS_OD_TL",
			"CUP_V_PMC_CIRAS_Black_TL",
			"CUP_V_PMC_CIRAS_Coyote_TL",
			"CUP_V_PMC_CIRAS_OD_Patrol",
			"CUP_V_PMC_CIRAS_Black_Patrol",
			"CUP_V_PMC_CIRAS_Coyote_Patrol",
		// CUP CPC ==================================================
			"CUP_V_CPC_light_coy",
			"CUP_V_CPC_lightbelt_coy",
			"CUP_V_CPC_light_rngr",
			"CUP_V_CPC_lightbelt_rngr",
			"CUP_V_CPC_Fast_coy",
			"CUP_V_CPC_Fastbelt_coy",
			"CUP_V_CPC_Fast_rngr",
			"CUP_V_CPC_Fastbelt_rngr",
			"CUP_V_CPC_tl_coy",
			"CUP_V_CPC_tlbelt_coy",
			"CUP_V_CPC_tl_rngr",
			"CUP_V_CPC_tlbelt_rngr",
		// CUP GER ==================================================
			"CUP_V_B_Armatus_Black",
			"CUP_V_B_Armatus_BB_Black",
			"CUP_V_B_Armatus_Coyote",
			"CUP_V_B_Armatus_BB_Coyote",
			"CUP_V_B_GER_Armatus_Fleck",
			"CUP_V_B_GER_Armatus_BB_Fleck",
			"CUP_V_B_Armatus_OD",
			"CUP_V_B_Armatus_BB_OD",
			"CUP_V_B_GER_Armatus_Trop",
			"CUP_V_B_GER_Armatus_BB_Trop",
			"CUP_V_B_GER_Vest_1",
			"CUP_V_B_GER_Vest_2",
			"CUP_V_B_GER_Carrier_Vest_3",
			"CUP_V_B_JPC_Fleck_Light",
			"CUP_V_B_JPC_Trop_Light",
			"CUP_V_B_LBT_LBV_Black",
			"CUP_V_B_LBT_LBV_Coyote",
			"CUP_V_B_GER_Carrier_Vest",
			"CUP_V_B_LBT_LBV_GRN",
			"CUP_V_B_LBT_LBV_OD",
			"CUP_V_B_GER_Carrier_Vest_2",
			"CUP_V_B_GER_Carrier_Rig_2_Brown",
			"CUP_V_B_GER_Carrier_Rig_3_Brown",
			"CUP_V_B_GER_Carrier_Rig_2",
			"CUP_V_B_GER_Carrier_Rig",
			"CUP_V_B_GER_PVest_Fleck_OFC",
			"CUP_V_B_GER_PVest_Trop_OFC",
			"CUP_V_B_GER_PVest_Fleck_RFL",
			"CUP_V_B_GER_PVest_Fleck_RFL_LT",
			"CUP_V_B_GER_PVest_Trop_RFL",
			"CUP_V_B_GER_PVest_Trop_RFL_LT",
			"CUP_V_B_GER_PVest_Fleck_TL",
			"CUP_V_B_GER_PVest_Fleck_TL_LT",
			"CUP_V_B_GER_PVest_Trop_TL",
			"CUP_V_B_GER_PVest_Trop_TL_LT",
			"CUP_V_B_GER_Tactical_Fleck",
			"CUP_V_B_GER_Tactical_Trop",
			"CUP_V_B_GER_PVest_Fleck_MG",
			"CUP_V_B_GER_PVest_Fleck_MG_LT",
			"CUP_V_B_GER_PVest_Trop_MG",
			"CUP_V_B_GER_PVest_Trop_MG_LT",
		// CUP Interceptor ==================================================
			"CUP_V_B_Interceptor_Base_Coyote",
			"CUP_V_B_Interceptor_Base_DCU",
			"CUP_V_B_Interceptor_Base_Grey",
			"CUP_V_B_Interceptor_Base_M81",
			"CUP_V_B_Interceptor_Base_Olive",
			"CUP_V_B_Interceptor_Rifleman_Coyote",
			"CUP_V_B_Interceptor_Rifleman_DCU",
			"CUP_V_B_Interceptor_Rifleman_Grey",
			"CUP_V_B_Interceptor_Rifleman_M81",
			"CUP_V_B_Interceptor_Rifleman_Olive",
		// CUP IOTV ==================================================
			"CUP_V_B_IOTV_UCP_Empty_USArmy",
			"CUP_V_B_IOTV_UCP_Rifleman_Deltoid_USArmy",
			"CUP_V_B_IOTV_UCP_Rifleman_USArmy",
			"CUP_V_B_IOTV_UCP_SL_USArmy",
			"CUP_V_B_IOTV_UCP_TL_USArmy",
			"CUP_V_B_IOTV_UCP_MG_USArmy",
			"CUP_V_PMC_IOTV_Black_AR",
			"CUP_V_PMC_IOTV_Coyote_AR",
			"CUP_V_PMC_IOTV_Black_Empty",
			"CUP_V_PMC_IOTV_Coyote_Empty",
			"CUP_V_PMC_IOTV_Black_Patrol",
			"CUP_V_PMC_IOTV_Coyote_Patrol",
			"CUP_V_PMC_IOTV_Black_TL",
			"CUP_V_PMC_IOTV_Coyote_TL",
		// CUP JPC ==================================================
			"CUP_V_JPC_Fast_coy",
			"CUP_V_JPC_Fastbelt_coy",
			"CUP_V_JPC_Fast_rngr",
			"CUP_V_JPC_Fastbelt_rngr",
			"CUP_V_B_JPC_Tan_Light",
			"CUP_V_JPC_lightbelt_coy",
			"CUP_V_B_JPC_OD_Light",
			"CUP_V_JPC_lightbelt_rngr",
			"CUP_V_JPC_tl_coy",
			"CUP_V_JPC_tlbelt_coy",
			"CUP_V_JPC_tl_rngr",
			"CUP_V_JPC_tlbelt_rngr",
		// CUP Takistani ==================================================
			"CUP_V_O_TK_Vest_1",
			"CUP_V_O_TK_CrewBelt",
		// CUP MBSS ==================================================
			"CUP_V_B_RRV_DA1_CB",
			"CUP_V_B_RRV_DA2_CB",
			"CUP_V_B_RRV_DA1",
			"CUP_V_B_RRV_DA2",
			"CUP_V_MBSS_PACA_Green",
			"CUP_V_MBSS_PACA2_Green",
			"CUP_V_MBSS_PACA_Black",
			"CUP_V_MBSS_PACA2_Black",
			"CUP_V_MBSS_PACA_CB",
			"CUP_V_MBSS_PACA2_CB",
			"CUP_V_MBSS_PACA_RGR",
			"CUP_V_MBSS_PACA2_RGR",
			"CUP_V_MBSS_PACA_Tan",
			"CUP_V_MBSS_PACA2_Tan",
		// CUP PASGT ==================================================
			"CUP_V_B_PASGT",
			"CUP_V_B_PASGT_no_bags",
			"CUP_V_B_PASGT_CCE",
			"CUP_V_B_PASGT_no_bags_CCE",
			"CUP_V_B_PASGT_OD",
			"CUP_V_B_PASGT_no_bags_OD",
			"CUP_V_B_PASGT_desert",
			"CUP_V_B_PASGT_no_bags_desert",
		// CUP RRV ==================================================
			"CUP_V_B_RRV_Light_CB",
			"CUP_V_B_RRV_Light",
			"CUP_V_B_RRV_Officer_CB",
			"CUP_V_B_RRV_Officer",
			"CUP_V_B_RRV_TL_CB",
			"CUP_V_B_RRV_TL",
			"CUP_V_B_RRV_MG",
			"CUP_V_B_RRV_MG_GRN",
			"CUP_V_B_Delta_1",
			"CUP_V_B_Delta_2",
		// CUP SPC ==================================================
			"CUP_V_B_Eagle_SPC_Empty",
			"CUP_V_B_Eagle_SPC_Officer",
			"CUP_V_B_Eagle_SPC_SL",
			"CUP_V_B_Eagle_SPC_TL",
			"CUP_V_B_Eagle_SPC_Patrol",
			"CUP_V_B_Eagle_SPC_RTO",
			"CUP_V_B_Eagle_SPC_MG"
];

_backpack = [
	// ======================================================================
	// Vanilla
	// ======================================================================
		// "Common" =========================================================
			"B_Parachute"	,
			"B_CombinationUnitRespirator_01_F"	,
			"B_SCBA_01_F"	,
		// "Light" ==========================================================
			"B_AssaultPack_blk"	,
			"B_AssaultPack_dgtl"	,
			"B_AssaultPack_rgr"	,
			"B_AssaultPack_khk"	,
			"B_AssaultPack_sgg"	,
			"B_AssaultPack_tna_F"	,
			"B_AssaultPack_eaf_F"	,
			"B_AssaultPack_wdl_F"	,
			"B_RadioBag_01_black_F"	,
			"B_RadioBag_01_digi_F"	,
			"B_RadioBag_01_eaf_F"	,
			"B_RadioBag_01_ghex_F"	,
			"B_RadioBag_01_tropic_F"	,
			"B_RadioBag_01_wdl_F"	,
			"B_LegStrapBag_black_F"	,
			"B_LegStrapBag_olive_F"	,
		// "Infantry" =======================================================
			"B_FieldPack_blk"	,
			"B_FieldPack_khk"	,
			"B_FieldPack_oli"	,
			"B_Kitbag_tan"		,
			"B_Kitbag_rgr"	,
			"B_Kitbag_sgg"	,
			"B_TacticalPack_blk"	,
			"B_TacticalPack_rgr"	,
			"B_TacticalPack_oli"	,
			"B_FieldPack_ghex_F"	,
			"B_ViperLightHarness_blk_F"	,
			"B_ViperLightHarness_ghex_F"	,
			"B_ViperLightHarness_khk_F"	,
			"B_ViperLightHarness_oli_F"	,
			"B_FieldPack_green_F"	,
			"B_FieldPack_taiga_F"	,
		// "Heavy" ==========================================================
			"B_Carryall_ocamo"  ,
			"B_Carryall_blk"    ,
			"B_Carryall_khk"	,
			"B_Carryall_oli"	,
			"B_Carryall_ghex_F"	,
			"B_ViperHarness_blk_F"	,
			"B_ViperHarness_ghex_F"	,
			"B_ViperHarness_khk_F"	,
			"B_ViperHarness_oli_F"	,
			"B_Carryall_eaf_F"	,
			"B_Carryall_green_F"	,
			"B_Carryall_taiga_F"	,
			"B_Carryall_wdl_F"	,
	// ======================================================================
	// SSU
	// ======================================================================
		// "Common" =========================================================
		// "Light" ==========================================================
			"B_SSU_Assault_Pack_AOR2"	,
			"B_SSU_Assault_Pack_MCAM_Black"	,
			"B_SSU_Assault_Pack_Black"	,
			"B_SSU_Assault_Pack_M81"	,
			"B_SSU_Assault_Pack_MCAM_Tropic"	,
			"B_SSU_Assault_Pack_MCAM_Woodland"	,
			"B_SSU_LegStrapBag_AOR2"	,
			"B_SSU_LegStrapBag_MCAM_Black"	,
			"B_SSU_LegStrapBag_Black"	,
			"B_SSU_LegStrapBag_M81"	,
			"B_SSU_LegStrapBag_MCAM_Tropic"	,
			"B_SSU_LegStrapBag_MCAM_Woodland"	,
			"B_SSU_RadioBag_AOR2"	,
			"B_SSU_RadioBag_MCAM_Black"	,
			"B_SSU_RadioBag_Black"	,
			"B_SSU_RadioBag_M81"	,
			"B_SSU_RadioBag_MCAM_Tropic"	,
			"B_SSU_RadioBag_MCAM_Woodland"	,
		// "Infantry" =======================================================
			"B_SSU_Kitbag_AOR2"	,
			"B_SSU_Kitbag_MCAM_Black"	,
			"B_SSU_Kitbag_Black"	,
			"B_SSU_Kitbag_M81"	,
			"B_SSU_Kitbag_MCAM_Tropic"	,
			"B_SSU_Kitbag_MCAM_Woodland"	,
			"B_SSU_TacticalPack_AOR2"	,
			"B_SSU_TacticalPack_MCAM_Black"	,
			"B_SSU_TacticalPack_Black"	,
			"B_SSU_TacticalPack_M81"	,
			"B_SSU_TacticalPack_MCAM_Tropic"	,
			"B_SSU_TacticalPack_MCAM_Woodland"	,
			"B_SSU_Viper_Light_Harness_AOR2"	,
			"B_SSU_Viper_Light_Harness_MCAM_Black"	,
			"B_SSU_Viper_Light_Harness_Black"	,
			"B_SSU_Viper_Light_Harness_M81"	,
			"B_SSU_Viper_Light_Harness_MCAM_Tropic"	,
			"B_SSU_Viper_Light_Harness_MCAM_Woodland"	,
		// "Heavy" ==========================================================
			"B_SSU_Viper_Harness_AOR2"	,
			"B_SSU_Viper_Harness_MCAM_Black"	,
			"B_SSU_Viper_Harness_Black"	,
			"B_SSU_Viper_Harness_M81"	,
			"B_SSU_Viper_Harness_MCAM_Tropic"	,
			"B_SSU_Viper_Harness_MCAM_Woodland"	,
	// ======================================================================
	// AGE
	// ======================================================================
		// "Common" ===============================================
		// "Light" ================================================
			"AGE_Banger_Backpouches_Olive"		,
			"AGE_LV119_Backpouches_SL_Black"		,
			"AGE_LV119_Backpouches_Black"		,
			"AGE_LV119_Backpouches_SL_TaigaD"		,
			"AGE_LV119_Backpouches_TaigaD"		,
			"AGE_LV119_Backpouches_SL_TaigaW"		,
			"AGE_LV119_Backpouches_TaigaW"		,
		// "Infantry" =============================================
		// "Heavy" ================================================
			"AGE_Backpack_Ares_Olive"		,
			"AGE_Camelback_Coyote"		,
	// ======================================================================
	// AEW
	// ======================================================================
		// "Common" ===============================================
		// "Light" ================================================
			"NAA_bac_ass_pouches_alpat_1"	,
			"NAA_bac_ass_alpat_ard1"	,
			"HEL_HEL_AssaultPack_1"	,
			"HEL_AssaultPack_khk_pouches_1"	,
			"AEW_backpack_Robin"	,
			"NAA_Radio_Backpack_F"	,
			"HEL_Radio_Backpack_F"	,
		// "Infantry" =============================================
			"NAA_bac_kit_alpat_ard1"	,
			"NAA_bac_tac_alpat_ard1"	,
		// "Heavy" ================================================
			"NAA_bac_carryAll_alpat_ard1"	,
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP RUS ==================================================
			"CUP_O_RUS_Patrol_bag_BeigeDigital",
			"CUP_O_RUS_Patrol_bag_BeigeDigital_Shovel",
			"CUP_O_RUS_Patrol_bag_Green",
			"CUP_O_RUS_Patrol_bag_Green_Shovel",
			"CUP_O_RUS_Patrol_bag_Summer",
			"CUP_O_RUS_Patrol_bag_Summer_Shovel",
			"CUP_O_RUS_Patrol_bag_Desert",
			"CUP_O_RUS_Patrol_bag_Desert_Shovel",
			"CUP_B_RUS_Backpack",
		// CUP GER ==================================================
			"CUP_B_GER_Pack_Flecktarn",
			"CUP_B_GER_Pack_Tropentarn",
		// CUP ACR ==================================================
			"CUP_B_ACRScout_m95",
			"CUP_B_ACRPara_dpm",
			"CUP_B_ACRPara_m95",
		// CUP US ==================================================
			"CUP_B_USPack_Coyote",
			"CUP_B_USPack_Black",
			"CUP_B_US_Assault_OCP",
			"CUP_B_US_Assault_OEFCP",
			"CUP_B_US_Assault_UCP",
			"CUP_B_US_IIID_OCP",
			"CUP_B_US_IIID_OEFCP",
			"CUP_B_US_IIID_UCP",
		// CUP USMC ==================================================
			"CUP_B_USMC_AssaultPack",
			"CUP_B_USMC_MOLLE",
			"CUP_B_USMC_MOLLE_WDL",
		// CUP Other ==================================================
			"CUP_B_Motherlode_MTP",
			"CUP_B_Motherlode_Radio_MTP",
			"CUP_B_Predator_MTP",
			"CUP_B_Predator_Radio_MTP",
			"CUP_B_AssaultPack_Coyote",
			"CUP_B_AssaultPack_Black",
			"CUP_B_AssaultPack_ACU",
			"CUP_B_Kombat_Olive",
			"CUP_B_Kombat_Radio_Olive",
			"CUP_B_TacticalPack_CCE",
			"CUP_B_TacticalPack_TTS",
			"CUP_B_Bergen_BAF",
			"CUP_B_AlicePack_Khaki",
			"CUP_B_AlicePack_OD",
			"CUP_B_AlicePack_Bedroll"
];

_headgear = [
	// ======================================================================
	// Vanilla
	// ======================================================================
		// "0" ==============================================================
			"H_Bandanna_camo"	,
			"H_Bandanna_gry"	,
			"H_Bandanna_khk"	,
			"H_Bandanna_khk_hs"	,
			"H_Bandanna_sgg"	,
			"H_Beret_blk"	,
			"H_Beret_CSAT_01_F"	,
			"H_Beret_EAF_01_F"	,
			"H_Booniehat_eaf"	,
			"H_Booniehat_khk"	,
			"H_Booniehat_khk_hs"	,
			"H_Booniehat_mgrn"	,
			"H_Booniehat_oli"	,
			"H_Booniehat_taiga"	,
			"H_Booniehat_tna_F"	,
			"H_Booniehat_wdl"	,
			"H_Cap_blk"	,
			"H_Cap_grn"	,
			"H_Cap_blk_Raven"	,
			"H_Cap_headphones"	,
			"H_Cap_oli"	,
			"H_Cap_oli_hs"	,
			"H_Hat_camo"	,
			"H_MilCap_eaf"	,
			"H_MilCap_ghex_F"	,
			"H_MilCap_grn"	,
			"H_MilCap_gry"	,
			"H_MilCap_taiga"	,
			"H_MilCap_tna_F"	,
			"H_MilCap_wdl"	,
			"H_Watchcap_blk"	,
			"H_Watchcap_camo"	,
			"H_Watchcap_khk"	,
			"H_WirelessEarpiece_F"	,
		// "I" ==============================================================
			"H_HelmetB_light"	,
			"H_HelmetB_light_black"	,
			"H_HelmetB_light_grass"	,
			"H_HelmetB_light_snakeskin"	,
			"H_HelmetB_Light_tna_F"	,
			"H_HelmetB_light_wdl"	,
		// "II" =============================================================
			"H_HelmetB"	,
			"H_HelmetB_black"	,
			"H_HelmetB_grass"	,
			"H_HelmetB_plain_wdl"	,
			"H_HelmetB_snakeskin"	,
			"H_HelmetB_tna_F"	,
			"H_HelmetHBK_ear_F"	,
			"H_HelmetHBK_F"	,
			"H_HelmetHBK_headset_F"	,
			"H_HelmetIA"	,
		// "II+" ============================================================
			"H_HelmetB_TI_tna_F"	,
			"H_HelmetB_TI_arid_F"	,
			"H_HelmetHBK_chops_F"	,
		// "III" ============================================================
			"H_HelmetLeaderO_ocamo" ,
			"H_HelmetO_ghex_F"	,
		// "IV" =============================================================
			"H_HelmetAggressor_cover_F"	,
			"H_HelmetAggressor_cover_taiga_F"	,
			"H_HelmetAggressor_F"	,
			"H_HelmetB_Enh_tna_F"	,
			"H_HelmetSpecB"	,
			"H_HelmetSpecB_blk"	,
			"H_HelmetSpecB_paint1"	,
			"H_HelmetSpecB_snakeskin"	,
			"H_HelmetSpecB_wdl"	,
			"H_HelmetSpecO_blk"	,
	// ======================================================================
	// SSU
	// ======================================================================
		// "0" ====================================================
			"H_SSU_Boonie_HS_AOR2"	,
			"H_SSU_Boonie_HS_MCAM_Black"	,
			"H_SSU_Boonie_HS_Black"	,
			"H_SSU_Boonie_HS_M81"	,
			"H_SSU_Boonie_HS_MCAM_Tropic"	,
			"H_SSU_Boonie_HS_MCAM_Woodland"	,
			"H_SSU_Cap_HS_AOR2"	,
			"H_SSU_Cap_HS_MCAM_Black"	,
			"H_SSU_Cap_HS_Black"	,
			"H_SSU_Cap_HS_M81"	,
			"H_SSU_Cap_HS_MCAM_Tropic"	,
			"H_SSU_Cap_HS_MCAM_Woodland"	,
		// "I" ====================================================
			"H_SSU_Light_Combat_Helmet_AOR2"	,
			"H_SSU_Light_Combat_Helmet_MCAM_Black"	,
			"H_SSU_Light_Combat_Helmet_Black"	,
			"H_SSU_Light_Combat_Helmet_M81"	,
			"H_SSU_Light_Combat_Helmet_MCAM_Tropic"	,
			"H_SSU_Light_Combat_Helmet_MCAM_Woodland"	,
		// "II" ===================================================
			"H_SSU_Advanced_Modular_Helmet_HS_AOR2"	,
			"H_SSU_Advanced_Modular_Helmet_Ear_AOR2"	,
			"H_SSU_Advanced_Modular_Helmet_HS_MCAM_Black"	,
			"H_SSU_Advanced_Modular_Helmet_Ear_MCAM_Black"	,
			"H_SSU_Advanced_Modular_Helmet_HS_Black"	,
			"H_SSU_Advanced_Modular_Helmet_Ear_Black"	,
			"H_SSU_Advanced_Modular_Helmet_HS_M81"	,
			"H_SSU_Advanced_Modular_Helmet_Ear_M81"	,
			"H_SSU_Advanced_Modular_Helmet_HS_MCAM_Tropic"	,
			"H_SSU_Advanced_Modular_Helmet_Ear_MCAM_Tropic"	,
			"H_SSU_Advanced_Modular_Helmet_HS_MCAM_Woodland"	,
			"H_SSU_Advanced_Modular_Helmet_Ear_MCAM_Woodland"	,
			"H_SSU_Combat_Helmet_AOR2"	,
			"H_SSU_Camo_Combat_Helmet_AOR2"	,
			"H_SSU_Combat_Helmet_MCAM_Black"	,
			"H_SSU_Camo_Combat_Helmet_MCAM_Black"	,
			"H_SSU_Combat_Helmet_Black"	,
			"H_SSU_Camo_Combat_Helmet_Black"	,
			"H_SSU_Combat_Helmet_M81"	,
			"H_SSU_Camo_Combat_Helmet_M81"	,
			"H_SSU_Combat_Helmet_MCAM_Tropic"	,
			"H_SSU_Camo_Combat_Helmet_MCAM_Tropic"	,
			"H_SSU_Combat_Helmet_MCAM_Woodland"	,
			"H_SSU_Camo_Combat_Helmet_MCAM_Woodland"	,
		// "II+" ==================================================
			"H_SSU_Advanced_Modular_Helmet_Chops_AOR2"	,
			"H_SSU_Advanced_Modular_Helmet_Chops_MCAM_Black"	,
			"H_SSU_Advanced_Modular_Helmet_Chops_Black"	,
			"H_SSU_Advanced_Modular_Helmet_Chops_M81"	,
			"H_SSU_Advanced_Modular_Helmet_Chops_MCAM_Tropic"	,
			"H_SSU_Advanced_Modular_Helmet_Chops_MCAM_Woodland"	,
			"H_SSU_Stealth_Combat_Helmet_AOR2"	,
			"H_SSU_Stealth_Combat_Helmet_MCAM_Black"	,
			"H_SSU_Stealth_Combat_Helmet_Black"	,
			"H_SSU_Stealth_Combat_Helmet_Black_b"	,
			"H_SSU_Stealth_Combat_Helmet_M81"	,
			"H_SSU_Stealth_Combat_Helmet_MCAM_Tropic"	,
			"H_SSU_Stealth_Combat_Helmet_MCAM_Woodland"	,
		// "IV" ===================================================
			"H_SSU_Enhanced_Combat_Helmet_AOR2"	,
			"H_SSU_Enhanced_Combat_Helmet_MCAM_Black"	,
			"H_SSU_Enhanced_Combat_Helmet_Black"	,
			"H_SSU_Enhanced_Combat_Helmet_M81"	,
			"H_SSU_Enhanced_Combat_Helmet_MCAM_Tropic"	,
			"H_SSU_Enhanced_Combat_Helmet_MCAM_Woodland"	,
	// ======================================================================
	// AGE
	// ======================================================================
		// "0" ====================================================
			"AGE_Beret_Alpha_Red"		,
			"AGE_ComTacs"		,
			"AGE_ComTacs_Facemask"		,
		// "II" ===================================================
			"AGE_ACH_Olive_C"		,
			"AGE_Fast_Black"		,
			"AGE_Fast_Black_A_L"		,
			"AGE_Fast_Black_H"		,
			"AGE_Fast_Black_H_A_L"		,
			"AGE_Fast_Black_P"		,
			"AGE_Fast_Black_P_A_L"		,
			"AGE_Kiver_Black"		,
			"AGE_Kiver_Black_VU"		,
			"AGE_Kiver_C_AtacsFG"		,
			"AGE_Kiver_C_AtacsFG_VU"		,
			"AGE_LSHZHC_Black"		,
			"AGE_LSHZHC_Black_C_ATACS"		,
			"AGE_LSHZHC_Black_C_ATACS_H"		,
			"AGE_LSHZHC_Black_H"		,
			"AGE_LSHZ_Black"		,
			"AGE_LSHZ_Black_C_Atacs"		,
			"AGE_LSHZ_Black_C_Atacs_H"		,
			"AGE_LSHZ_Black_C_Atacs_H_A"		,
			"AGE_LSHZ_Black_C_Atacs_H_A_L"		,
			"AGE_LSHZ_Black_C_Atacs_H_A_VU"		,
			"AGE_LSHZ_Black_C_Atacs_H_L"		,
			"AGE_LSHZ_Black_H"		,
			"AGE_LSHZ_Black_H_A"		,
			"AGE_LSHZ_Black_H_A_L"		,
			"AGE_LSHZ_Black_L"		,
			"AGE_LSHZ_BlackMCam_H_A"		,
			"AGE_LSHZ_BlackMCam_H_A_L"		,
			"AGE_LSHZ_Olive"		,
			"AGE_LSHZ_Black_C_Atacs_L"		,
			"AGE_LSHZ_Olive_H"		,
			"AGE_LSHZ_Olive_H_A"		,
			"AGE_LSHZ_Olive_H_A_L"		,
			"AGE_LSHZ_Olive_L"		,
			"AGE_LSHZ_Painted"		,
			"AGE_LSHZ_Painted_H"		,
			"AGE_LSHZ_Painted_H_A"		,
			"AGE_LSHZ_Painted_H_A_L"		,
			"AGE_LSHZ_Painted_L"		,
			"AGE_LSHZ_PaintedMCam_H_A"		,
			"AGE_LSHZ_PaintedMCam_H_A_L"		,
			"AGE_MICH_Olive_H_A"		,
			"AGE_PASGT_Flora"		,
			"AGE_PASGT_Flora_G"		,
			"AGE_PASGT_Olive"		,
			"AGE_PASGT_Summer"		,
			"AGE_PASGT_Summer_G"		,
			"AGE_Fast_Olive"		,
			"AGE_Fast_Olive_H"		,
			"AGE_Fast_Olive_P"		,
			"AGE_Fast_Olive_CTaigaW"		,
			"AGE_Fast_Olive_CTaigaW_H"		,
			"AGE_Fast_Olive_CTaigaW_P"		,
			"AGE_Fast_Tan_CTaigaD"		,
			"AGE_Fast_Tan_CTaigaD_H"		,
			"AGE_Fast_Tan_CTaigaD_P"		,
		// "II+" ==================================================
			"AGE_Kiver_Black_V"		,
			"AGE_Kiver_C_AtacsFG_V"		,
			"AGE_LSHZ_Black_C_Atacs_H_A_V"		,
		// "V" ====================================================
			"AGE_Altyn_Black"		,
			"AGE_Altyn_Black_C"		,
			"AGE_Altyn_Black_C_VU"		,
			"AGE_Altyn_Black_VU"		,
			"AGE_Altyn_Olive"		,
			"AGE_Altyn_Olive_C"		,
			"AGE_Altyn_Olive_C_VU"		,
			"AGE_Altyn_Olive_VU"		,
		// "V+" ===================================================
			"AGE_Altyn_Black_C_V"		,
			"AGE_Altyn_Black_V"		,
			"AGE_Altyn_Olive_C_V"		,
			"AGE_Altyn_Olive_V"		,
	// ======================================================================
	// AEW
	// ======================================================================
		// "0" ====================================================
			"GUR_beret_01"	,
			"HEL_beret_1"	,
			"HEL_hat_boonie_1"	,
			"HEL_hat_boonie_1_hs"	,
			"HEL_hat_milcap_1"	,
			"MYR_cap_blk"	,
			"MYR_cap_headphones"	,
			"MYR_cap_hs"	,
			"NAA_beret"	,
			"NAA_beret_02"	,
			"NAA_hat_boonie_alpat_ard1"	,
			"NAA_hat_boonie_alpat_wdl1"	,
			"NAA_hat_boonie_hs_alpat_ard1"	,
			"NAA_hat_boonie_hs_alpat_wdl1"	,
			"NAA_hat_cap_alpat_ard1"	,
			"NAA_hat_milcap_alpat_ard1"	,
			"NAA_hat_milcap_alpat_wdl1"	,
		// "I" ====================================================
			"HEL_hel_lgt_1"	,
			"MYR_hel_lgt_1"	,
			"NAA_hel_lgt_1_F"	,
			"NAA_hel_lgt_2_F"	,
			"NAA_hel_lgt_aplat_F"	,
			"NAA_hel_lgt_aplat_hades"	,
		// "II" ===================================================
			"CSAT_NA_PASGT_1_F"	,
			"CSAT_NA_PASGT_2_F"	,
			"GUR_hel_black"	,
			"HEL_hel_ech_1"	,
			"MYR_basic_helmet_gray"	,
			"MYR_hel_ech_1"	,
			"NAA_hel_can_alpat_ard1"	,
			"NAA_hel_can_alpat_wdl1"	,
			"NAA_hel_ech_alpat_ard1"	,
			"NAA_hel_ech_alpat_MP_02"	,
		// "III" ==================================================
			"CSAT_NA_PASGT_neckprot_1_F"	,
			"CSAT_NA_PASGT_neckprot_2_F"	,
		// "IV" ===================================================
			"HEL_hel_camo_1"	,
			"HEL_hel_sf_1"	,
			"MYR_hel_sf_1"	,
			"NAA_hel_camo_alpat_ard1"	,
			"NAA_hel_camo_alpat_wdl"	,
			"NAA_hel_ech_alpat_MP_01"	,
			"NAA_hel_sf_alpat_ard1"	,
			"NAA_hel_sf_alpat_ard2"	,
			"NAA_hel_sf_alpat_hades"	,
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP ACH ==================================================
			"CUP_H_HIL_HelmetACH_CCE",
			"CUP_H_HIL_HelmetACH_Headset_CCE",
			"CUP_H_HIL_HelmetACH_ESS_CCE",
			"CUP_H_HIL_HelmetACH_ESS_Headset_CCE",
			"CUP_H_HIL_HelmetACH_GCovered_CCE",
			"CUP_H_HIL_HelmetACH_GCovered_Headset_CCE",
			"CUP_H_Booniehat_CCE",
			"CUP_H_USArmy_HelmetACH_OCP",
			"CUP_H_USArmy_HelmetACH_GCOVERED_OCP",
			"CUP_H_USArmy_HelmetACH_GCOVERED_Headset_OCP",
			"CUP_H_USArmy_HelmetACH_ESS_OCP",
			"CUP_H_USArmy_HelmetACH_ESS_Headset_OCP",
			"CUP_H_USArmy_HelmetACH_Headset_OCP",
			"CUP_H_USArmy_Boonie_OCP",
			"CUP_H_USArmy_Boonie_hs_OCP",
			"CUP_H_HIL_HelmetACH_TTS",
			"CUP_H_HIL_HelmetACH_Headset_TTS",
			"CUP_H_HIL_HelmetACH_ESS_TTS",
			"CUP_H_HIL_HelmetACH_ESS_Headset_TTS",
			"CUP_H_HIL_HelmetACH_GCovered_TTS",
			"CUP_H_HIL_HelmetACH_GCovered_Headset_TTS",
			"CUP_H_Booniehat_TTS",
			"CUP_H_USArmy_HelmetACH_UCP",
			"CUP_H_USArmy_HelmetACH_GCOVERED_UCP",
			"CUP_H_USArmy_HelmetACH_GCOVERED_Headset_UCP",
			"CUP_H_USArmy_HelmetACH_ESS_UCP",
			"CUP_H_USArmy_HelmetACH_ESS_Headset_UCP",
			"CUP_H_USArmy_HelmetACH_Headset_UCP",
			"CUP_H_USArmy_Boonie_UCP",
			"CUP_H_USArmy_Boonie_hs_UCP",
			"CUP_H_USArmy_Helmet_ECH1_Black",
			"CUP_H_USArmy_Helmet_ECH2_Black",
			"CUP_H_USArmy_Helmet_ECH1_Green",
			"CUP_H_USArmy_Helmet_ECH2_GREEN",
			"CUP_H_USArmy_ECH_MARPAT_des",
			"CUP_H_USArmy_ECH_GCOVEREDMARPAT_des",
			"CUP_H_USArmy_ECH_GCOVERED_Headset_MARPAT_des",
			"CUP_H_USArmy_ECH_ESS_MARPAT_des",
			"CUP_H_USArmy_ECH_ESS_Headset_MARPAT_des",
			"CUP_H_USArmy_ECH_Headset_MARPAT_des",
			"CUP_H_USArmy_ECH_MARPAT",
			"CUP_H_USArmy_ECH_Headset_MARPAT",
			"CUP_H_USArmy_ECH_ESS_MARPAT",
			"CUP_H_USArmy_ECH_ESS_Headset_MARPAT",
			"CUP_H_USArmy_ECH_GCOVERED_MARPAT",
			"CUP_H_USArmy_ECH_GCOVERED_Headset_MARPAT",
			"CUP_H_USArmy_Helmet_ECH1_Sand",
			"CUP_H_USArmy_Helmet_ECH2_Sand",
			"CUP_H_USArmy_Helmet_M1_plain_Olive",
			"CUP_H_USArmy_Helmet_M1_plain_Vine",
			"CUP_H_USArmy_Helmet_M1_plain_M81",
			"CUP_H_USArmy_MICH_M81",
			"CUP_H_USArmy_MICH_Headset_M81",
			"CUP_H_USArmy_MICH_ESS_M81",
			"CUP_H_USArmy_MICH_ESS_Headset_M81",
			"CUP_H_USArmy_MICH_GCOVERED_M81",
			"CUP_H_USArmy_MICH_GCOVERED_Headset_M81",
			"CUP_H_USArmy_MICH_UCP",
			"CUP_H_USArmy_MICH_GCOVERED_UCP",
			"CUP_H_USArmy_MICH_GCOVERED_Headset_UCP",
			"CUP_H_USArmy_MICH_ESS_UCP",
			"CUP_H_USArmy_MICH_ESS_Headset_UCP",
			"CUP_H_USArmy_MICH_Headset_UCP",
			"CUP_H_USArmy_Helmet_Protec",
			"CUP_H_USArmy_Helmet_Protec_Gog",
			"CUP_H_USArmy_Helmet_Protec_Gog_Strb",
			"CUP_H_USArmy_Helmet_Protec_NVG",
		// CUP ACR ==================================================
			"CUP_H_CZ_Hat01",
			"CUP_H_CZ_Hat02",
			"CUP_H_CZ_Hat03",
			"CUP_H_CZ_Booniehat_vz95_des",
			"CUP_H_CZ_Booniehat_fold_des",
			"CUP_H_CZ_Cap_flag",
			"CUP_H_CZ_Cap_Headphones",
			"CUP_H_CZ_Cap_khk",
			"CUP_H_CZ_Cap_Headphones_des",
			"CUP_H_CZ_Cap_rgr",
			"CUP_H_CZ_Hat04",
			"CUP_H_CZ_Helmet01",
			"CUP_H_CZ_Helmet02",
			"CUP_H_CZ_Helmet03",
			"CUP_H_CZ_Helmet04",
			"CUP_H_CZ_Helmet07",
			"CUP_H_CZ_Helmet08",
			"CUP_H_CZ_Helmet09",
			"CUP_H_CZ_Helmet10",
			"CUP_H_CZ_Patrol_Cap",
		// CUP CDF ==================================================
			"CUP_H_CDF_Beret_UN",
			"CUP_H_CDF_OfficerCap_DST",
			"CUP_H_CDF_OfficerCap_MNT",
			"CUP_H_CDF_OfficerCap_FST",
			"CUP_H_CDF_OfficerCap_SNW",
			"CUP_H_CDF_H_PASGT_DST",
			"CUP_H_CDF_H_PASGT_FST",
			"CUP_H_CDF_H_PASGT_MNT",
			"CUP_H_CDF_H_PASGT_SNW",
		// CUP ChDKZ ==================================================
			"CUP_H_ChDKZ_Beanie",
			"CUP_H_ChDKZ_Beret",
			"CUP_H_ChDKZ_Cap",
		// CUP FR ==================================================
			"CUP_H_FR_BandanaGreen",
			"CUP_H_FR_BandanaWdl",
			"CUP_H_FR_Bandana_Headset",
			"CUP_H_FR_BeanieGreen",
			"CUP_H_FR_Boonie_DES",
			"CUP_H_FR_BoonieMARPAT",
			"CUP_H_FR_BoonieWDL",
			"CUP_H_FR_PRR_BoonieWDL",
			"CUP_H_FR_Cap_Headset_Green",
			"CUP_H_FR_Cap_Officer_Headset",
			"CUP_H_FR_ECH",
		// CUP GER ==================================================
			"CUP_H_Ger_Beret_INF_Grn",
			"CUP_H_Ger_Beret_KSK_Red",
			"CUP_H_Ger_Beret_ARM_Grn",
			"CUP_H_Ger_Beret_ARM_Blk",
			"CUP_H_Ger_Boonie_Flecktarn",
			"CUP_H_Ger_Boonie2_Flecktarn",
			"CUP_H_Ger_Boonie_desert",
			"CUP_H_Ger_Boonie2_desert",
			"CUP_H_Ger_Cap_EP_Grn2",
			"CUP_H_Ger_Cap_EP_Grn1",
			"CUP_H_Ger_Cap_Grn2",
			"CUP_H_Ger_Cap_Grn1",
			"CUP_H_Ger_Cap_EP_Tan2",
			"CUP_H_Ger_Cap_EP_Tan1",
			"CUP_H_Ger_Cap_Tan2",
			"CUP_H_Ger_Cap_Tan1",
			"CUP_H_Ger_M92_Black",
			"CUP_H_Ger_M92_Black_GG",
			"CUP_H_Ger_M92_Black_GG_CF",
			"CUP_H_Ger_M92_Black_GG_CB",
			"CUP_H_Ger_M92_Cover",
			"CUP_H_Ger_M92_Cover_GG",
			"CUP_H_Ger_M92_Cover_GG_CF",
			"CUP_H_Ger_M92_Cover_GG_CB",
			"CUP_H_Ger_M92",
			"CUP_H_Ger_M92_GG",
			"CUP_H_Ger_M92_GG_CF",
			"CUP_H_Ger_M92_GG_CB",
			"CUP_H_Ger_M92_RGR",
			"CUP_H_Ger_M92_RGR_GG",
			"CUP_H_Ger_M92_RGR_GG_CF",
			"CUP_H_Ger_M92_RGR_GG_CB",
			"CUP_H_Ger_M92_Tan",
			"CUP_H_Ger_M92_Tan_GG",
			"CUP_H_Ger_M92_Tan_GG_CB",
			"CUP_H_Ger_M92_Tan_GG_CF",
			"CUP_H_Ger_M92_Cover_Trop",
			"CUP_H_Ger_M92_Cover_Trop_GG_CB",
			"CUP_H_Ger_M92_Cover_Trop_GG_CF",
			"CUP_H_Ger_M92_Cover_Trop_GG",
		// CUP LWH ==================================================
			"CUP_H_LWHv2_brown",
			"CUP_H_LWHv2_brown_comms",
			"CUP_H_LWHv2_brown_ess_comms",
			"CUP_H_LWHv2_desert",
			"CUP_H_LWHv2_desert_comms",
			"CUP_H_LWHv2_desert_ess_comms",
			"CUP_H_LWHv2_ERDL_lowland",
			"CUP_H_LWHv2_ERDL_lowland_comms",
			"CUP_H_LWHv2_ERDL_lowland_ess_comms",
			"CUP_H_LWHv2_MARPAT_des",
			"CUP_H_LWHv2_MARPAT_des_comms",
			"CUP_H_LWHv2_MARPAT_des_cov_fr",
			"CUP_H_LWHv2_MARPAT_des_comms_cov_fr",
			"CUP_H_LWHv2_MARPAT_des_NVG_gog_cov2",
			"CUP_H_LWHv2_MARPAT_des_NVG_gog2_cov2",
			"CUP_H_LWHv2_MARPAT",
			"CUP_H_LWHv2_MARPAT_comms",
			"CUP_H_LWHv2_MARPAT_comms_cov_fr",
			"CUP_H_LWHv2_MARPAT_cov_fr",
			"CUP_H_LWHv2_MARPAT_NVG_gog_cov2",
			"CUP_H_LWHv2_MARPAT_NVG_gog2_cov2",
			"CUP_H_LWHv2_OD",
			"CUP_H_LWHv2_OD_comms",
			"CUP_H_LWHv2_OD_ess_comms",
			"CUP_H_LWHv2_Tpat",
			"CUP_H_LWHv2_Tpat_comms",
			"CUP_H_LWHv2_Tpat_ess_comms",
			"CUP_H_LWHv2_tigerstripe",
			"CUP_H_LWHv2_tigerstripe_comms",
			"CUP_H_LWHv2_tigerstripe_ess_comms",
		// CUP OpsCore ==================================================
			"CUP_H_OpsCore_Covered_AAF",
			"CUP_H_OpsCore_Covered_AAF_SF",
			"CUP_H_OpsCore_Covered_AAF_NoHS",
			"CUP_H_OpsCore_Black",
			"CUP_H_OpsCore_Black_SF",
			"CUP_H_OpsCore_Black_NoHS",
			"CUP_H_OpsCore_Covered_Fleck",
			"CUP_H_OpsCore_Covered_Fleck_SF",
			"CUP_H_OpsCore_Covered_Fleck_NoHS",
			"CUP_H_OpsCore_Green",
			"CUP_H_OpsCore_Green_SF",
			"CUP_H_OpsCore_Green_NoHS",
			"CUP_H_OpsCore_Grey",
			"CUP_H_OpsCore_Grey_SF",
			"CUP_H_OpsCore_Grey_NoHS",
			"CUP_H_OpsCore_Spray",
			"CUP_H_OpsCore_Spray_SF",
			"CUP_H_OpsCore_Spray_NoHS",
			"CUP_H_OpsCore_Covered_Tigerstripe",
			"CUP_H_OpsCore_Covered_Tigerstripe_SF",
			"CUP_H_OpsCore_Covered_Tigerstripe_NoHS",
			"CUP_H_OpsCore_Covered_Tropen",
			"CUP_H_OpsCore_Covered_Tropen_SF",
			"CUP_H_OpsCore_Covered_Tropen_NoHS",
			"CUP_H_OpsCore_Tan",
			"CUP_H_OpsCore_Tan_SF",
			"CUP_H_OpsCore_Tan_NoHS",
			"CUP_H_OpsCore_Covered_UCP",
			"CUP_H_OpsCore_Covered_UCP_SF",
			"CUP_H_OpsCore_Covered_UCP_NoHS",
		// CUP PASGT ==================================================
			"CUP_H_PASGTv2_DCU",
			"CUP_H_PASGTv2_desert",
			"CUP_H_PASGTv2_ERDL_highland",
			"CUP_H_PASGTv2_ERDL_lowland",
			"CUP_H_PASGTv2_WDL",
			"CUP_H_PASGTv2_WDL_CF",
			"CUP_H_PASGTv2_WDL_GG",
			"CUP_H_PASGTv2_NVG_WDL",
			"CUP_H_PASGTv2_NVG_WDL_GG",
			"CUP_H_PASGTv2_NVG_WDL_CF",
			"CUP_H_PASGTv2_NVG_WDL_GG_CB",
			"CUP_H_PASGTv2_NVG_DCU",
			"CUP_H_PASGTv2_NVG_desert",
			"CUP_H_PASGTv2_NVG_ERDL_highland",
			"CUP_H_PASGTv2_NVG_ERDL_lowland",
			"CUP_H_PASGTv2_tigerstripe",
			"CUP_H_PASGTv2_NVG_tigerstripe",
			"CUP_H_PASGTv2_OD",
			"CUP_H_PASGTv2_NVG_OD",
			"CUP_H_PASGTv2_TPattern",
			"CUP_H_PASGTv2_NVG_TPattern",
			"CUP_H_PASGTv2_Urban",
			"CUP_H_PASGTv2_NVG_Urban",
		// CUP PMC ==================================================
			"CUP_H_PMC_Beanie_Khaki",
			"CUP_H_PMC_Beanie_Black",
			"CUP_H_PMC_Beanie_Headphones_Khaki",
			"CUP_H_PMC_Beanie_Headphones_Black",
			"CUP_H_PMC_Cap_Grey",
			"CUP_H_PMC_Cap_PRR_Grey",
			"CUP_H_PMC_Cap_Back_PRR_Grey",
			"CUP_H_PMC_Cap_EP_Grey",
			"CUP_H_PMC_Cap_Back_EP_Grey",
			"CUP_H_PMC_Cap_Back_Grey",
			"CUP_H_PMC_Cap_Tan",
			"CUP_H_PMC_Cap_Back_Tan",
			"CUP_H_PMC_Cap_Back_EP_Tan",
			"CUP_H_PMC_Cap_Back_PRR_Tan",
			"CUP_H_PMC_Cap_EP_Tan",
			"CUP_H_PMC_Cap_PRR_Tan",
		// CUP RACS ==================================================
			"CUP_H_RACS_Beret_Blue",
		// CUP RUS ==================================================
			"CUP_H_RUS_6B27_cover_BeigeDigital",
			"CUP_H_RUS_6B27_cover_BeigeDigital_goggles",
			"CUP_H_RUS_6B27_cover_BeigeDigital_headset",
			"CUP_H_RUS_6B27_cover_BeigeDigital_headset_goggles",
			"CUP_H_RUS_6B46",
			"CUP_H_RUS_6B27_cover",
			"CUP_H_RUS_6B27_cover_headset",
			"CUP_H_RUS_6B27_cover_headset_goggles",
			"CUP_H_RUS_6B27_olive",
			"CUP_H_RUS_6B27_NVG_olive",
			"CUP_H_RUS_6B27",
			"CUP_H_RUS_6B27_NVG",
			"CUP_H_RUS_6B27_headset",
			"CUP_H_RUS_6B27_goggles",
			"CUP_H_RUS_6B27_headset_goggles",
			"CUP_H_RUS_6B47_v2_BeigeDigital",
			"CUP_H_RUS_6B47_v2_GogglesDown_BeigeDigital",
			"CUP_H_RUS_6B47_v2_GogglesUp_BeigeDigital",
			"CUP_H_RUS_6B47_v2_GogglesClosed_BeigeDigital",
			"CUP_H_RUS_6B47_v2_Summer",
			"CUP_H_RUS_6B47_v2_GogglesDown_Summer",
			"CUP_H_RUS_6B47_v2_GogglesUp_Summer",
			"CUP_H_RUS_6B47_v2_GogglesClosed_Summer",
			"CUP_H_RUS_6B47",
			"CUP_H_RUS_6B47_headset",
			"CUP_H_RUS_6B47_headset_goggles",
			"CUP_H_RUS_6B47_desert",
			"CUP_H_RUS_6B47_headset_desert",
			"CUP_H_RUS_6B47_goggles_desert",
			"CUP_H_RUS_6B47_headset_goggles_desert",
			"CUP_H_RUS_6B47_SF",
			"CUP_H_RUS_6B47_SF_headset",
			"CUP_H_RUS_6B47_SF_headset_desert",
			"CUP_H_RUS_6B47_SF_headset_goggles_desert",
			"CUP_H_RUS_6B47_SF_headset_goggles_black",
			"CUP_H_RUS_6B47_SF_headset_black",
			"CUP_H_RUS_Altyn",
			"CUP_H_RUS_Altyn_Shield_Up",
			"CUP_H_RUS_Altyn_Shield_Down",
			"CUP_H_RUS_Altyn_Goggles",
			"CUP_H_RUS_Altyn_black",
			"CUP_H_RUS_Altyn_Shield_Up_black",
			"CUP_H_RUS_Altyn_Shield_Down_black",
			"CUP_H_RUS_Altyn_Goggles_black",
			"CUP_H_RUS_Altyn_khaki",
			"CUP_H_RUS_Altyn_Shield_Up_khaki",
			"CUP_H_RUS_Altyn_Shield_Down_khaki",
			"CUP_H_RUS_Altyn_Goggles_khaki",
			"CUP_H_RUS_Bandana_GSSh_Headphones",
			"CUP_H_RUS_Bandana_HS",
			"CUP_H_RUS_Beret_VDV",
			"CUP_H_RUS_Beret_Spetsnaz",
			"CUP_H_RUS_K6_3",
			"CUP_H_RUS_K6_3_Shield_Up",
			"CUP_H_RUS_K6_3_Shield_Down",
			"CUP_H_RUS_K6_3_Goggles",
			"CUP_H_RUS_K6_3_black",
			"CUP_H_RUS_K6_3_Shield_Up_black",
			"CUP_H_RUS_K6_3_Shield_Down_black",
			"CUP_H_RUS_K6_3_Goggles_black",
			"CUP_H_RUS_K6_3_khaki",
			"CUP_H_RUS_K6_3_Shield_Up_khaki",
			"CUP_H_RUS_K6_3_Shield_Down_khaki",
			"CUP_H_RUS_K6_3_Goggles_khaki",
			"CUP_H_RUS_SSH68_olive",
			"CUP_H_RUS_SSH68_green",
			"CUP_H_RUS_SSH68_cover_vsr93",
			"CUP_H_RUS_SSH68_cover_vsr98",
			"CUP_H_RUS_SSH68_cover_vsr84_dubok",
			"CUP_H_RUS_SSH68_cover_berezka",
			"CUP_H_RUS_GSSh01_Headphones_black",
			"CUP_H_RUS_GSSh01_Headphones_brown",
			"CUP_H_RUS_GSSh01_Headphones_grey",
			"CUP_H_RUS_GSSh01_Headphones_green",
			"CUP_H_RUS_Cap_ATACSAU",
			"CUP_H_RUS_Cap_ATACSFG",
			"CUP_H_RUS_Cap_EMR",
		// CUP SLA ==================================================
			"CUP_H_SLA_BeanieGreen",
			"CUP_H_SLA_Beret",
			"CUP_H_SLA_BeretRed",
			"CUP_H_SLA_Boonie_DES",
			"CUP_H_SLA_Boonie_URB",
			"CUP_H_SLA_Boonie",
			"CUP_H_SLA_SLCap",
			"CUP_H_SLA_OfficerCap",
			"CUP_H_SLA_Helmet",
			"CUP_H_SLA_Helmet_DES",
			"CUP_H_SLA_Helmet_URB",
			"CUP_H_SLA_Helmet_BLK",
		// CUP Takistani ==================================================
			"CUP_H_TK_Beret",
		// CUP US ==================================================
			"CUP_H_US_BOONIE_Alpenflage",
			"CUP_H_USA_Boonie_wdl",
			"CUP_H_USA_Cap_M81",
			"CUP_H_US_patrol_cap_alpenflage",
			"CUP_H_US_patrol_cap_DCU",
			"CUP_H_US_patrol_cap_desert",
			"CUP_H_US_patrol_cap_ERDL_highland",
			"CUP_H_US_patrol_cap_ERDL",
			"CUP_H_US_patrol_cap_WDL",
			"CUP_H_US_patrol_cap_OD",
			"CUP_H_US_patrol_cap_tigerstripe",
			"CUP_H_US_patrol_cap_Tpattern",
			"CUP_H_US_patrol_cap_urban",
			"CUP_H_US_patrol_cap_UCP",
		// CUP USMC ==================================================
			"CUP_H_USMC_BOONIE_2_DES",
			"CUP_H_USMC_BOONIE_WDL",
			"CUP_H_USMC_BOONIE_PRR_DES",
			"CUP_H_USMC_BOONIE_PRR_WDL",
			"CUP_H_USMC_Officer_Cap",
			"CUP_H_USMC_CAP_WDL",
			"CUP_H_USMC_CAP_PRR_WDL",
			"CUP_H_USMC_CAP_DES",
			"CUP_H_USMC_CAP_PRR_DES",
			"CUP_H_BAF_DDPM_Mk6_GOGGLES_PRR",
			"CUP_H_BAF_DDPM_Mk6_NETTING_PRR",
			"CUP_H_BAF_DPM_Mk6_EMPTY_PRR",
			"CUP_H_BAF_DPM_Mk6_GOGGLES_PRR",
			"CUP_H_BAF_DPM_Mk6_NETTING_PRR",
			"CUP_H_BAF_MTP_Mk6_EMPTY",
			"CUP_H_BAF_MTP_Mk7",
			"CUP_H_BAF_MTP_Mk7_PRR_SCRIM_A",
			"CUP_H_BAF_MTP_Mk7_PRR_SCRIM_B",
			"CUP_H_BAF_MTP_Mk7_PRR",
			"CUP_H_BAF_MTP_Mk6_EMPTY_PRR",
			"CUP_H_BAF_MTP_Mk6_GOGGLES_PRR"
];

_googles = [
	// ======================================================================
	// Vanilla
	// ======================================================================
		// "All" ============================================================
			"G_Diving"	,
			"G_I_Diving"	,
			"G_O_Diving"	,
			"G_AirPurifyingRespirator_02_black_F"	,
			"G_AirPurifyingRespirator_02_olive_F"	,
			"G_AirPurifyingRespirator_01_F"	,
			"G_RegulatorMask_F"	,
		// "Other" ==========================================================
			"G_Aviator"	,
			"G_Balaclava_blk"	,
			"G_Balaclava_combat"	,
			"G_Balaclava_lowprofile"	,
			"G_Balaclava_oli"	,
			"G_Bandanna_aviator"	,
			"G_Bandanna_beast"	,
			"G_Bandanna_blk"	,
			"G_Bandanna_khk"	,
			"G_Bandanna_oli"	,
			"G_Combat"	,
			"G_Lowprofile"	,
			"G_Shades_Black"	,
			"G_Spectacles"	,
			"G_Squares_Tinted"	,
			"G_Squares"	,
			"G_Tactical_Clear"	,
			"G_Tactical_Black"	,
			"G_Spectacles_Tinted"	,
			"G_Goggles_VR"	,
			"G_Combat_Goggles_tna_F"	,
			"G_Balaclava_TI_blk_F"	,
			"G_Balaclava_TI_G_blk_F"	,
			"G_Balaclava_TI_tna_F"	,
			"G_Balaclava_TI_G_tna_F"	,
			"G_Respirator_white_F"	,
			"G_WirelessEarpiece_F"	,
	// ======================================================================
	// SSU
	// ======================================================================
		// "Other" ================================================
			"G_SSU_Bandana_AOR2",
			"G_SSU_Bandana_AOR2_Beast",
			"G_SSU_Bandana_Sports_AOR2",
			"G_SSU_Bandana_Sports_AOR2_Beast",
			"G_SSU_Bandana_MCAM_Black",
			"G_SSU_Bandana_MCAM_Black_Beast",
			"G_SSU_Bandana_Sports_MCAM_Black",
			"G_SSU_Bandana_Sports_MCAM_Black_Beast",
			"G_SSU_Bandana_Black",
			"G_SSU_Bandana_Black_Beast",
			"G_SSU_Bandana_Sports_Black",
			"G_SSU_Bandana_Sports_Black_Beast",
			"G_SSU_Bandana_M81",
			"G_SSU_Bandana_M81_Beast",
			"G_SSU_Bandana_Sports_M81",
			"G_SSU_Bandana_Sports_M81_Beast",
			"G_SSU_Bandana_MCAM_Tropic",
			"G_SSU_Bandana_MCAM_Tropic_Beast",
			"G_SSU_Bandana_Sports_MCAM_Tropic",
			"G_SSU_Bandana_Sports_MCAM_Tropic_Beast",
			"G_SSU_Bandana_MCAM_Woodland",
			"G_SSU_Bandana_MCAM_Woodland_Beast",
			"G_SSU_Bandana_Sports_MCAM_Woodland",
			"G_SSU_Bandana_Sports_MCAM_Woodland_Beast",
			"G_SSU_Balaclava_TI_AOR2",
			"G_SSU_Balaclava_TI_G_AOR2",
			"G_SSU_Balaclava_TI_MCAM_Black",
			"G_SSU_Balaclava_TI_G_MCAM_Black",
			"G_SSU_Balaclava_TI_Black",
			"G_SSU_Balaclava_TI_G_Black",
			"G_SSU_Balaclava_TI_M81",
			"G_SSU_Balaclava_TI_G_M81",
			"G_SSU_Balaclava_TI_MCAM_Tropic",
			"G_SSU_Balaclava_TI_G_MCAM_Tropic",
			"G_SSU_Balaclava_TI_MCAM_Woodland",
			"G_SSU_Balaclava_TI_G_MCAM_Woodland",
	// ======================================================================
	// AGE
	// ======================================================================
		// "Other" ================================================
			"AGE_Armband_Orange",
			"AGE_Armband_Yellow",
			"AGE_Balaclava_Black",
			"AGE_Balaclava_Olive",
			"AGE_Balaclava_Skull",
			"AGE_Goggles_ComTacs",
			"AGE_SPLAV_Gloves",
			"AGE_Goggles_CombatGoggles",
	// ======================================================================
	// AEW
	// ======================================================================
		// "Other" ================================================
			"GUR_Balaclava_combat",
			"GUR_Balaclava_combat_oli",
			"GUR_Balaclava_lowprofile_oli",
			"NAA_G_Combat_blk_amb_F",
			"NAA_G_Combat_blk_clr_F",
			"NAA_G_Combat_blk_drk_F",
			"NAA_G_Combat_brn_amb_F",
			"NAA_G_Combat_brn_clr_F",
			"NAA_G_Combat_brn_drk_F",
			"NAA_G_Combat_grn_amb_F",
			"NAA_G_Combat_grn_clr_F",
			"NAA_G_Combat_grn_drk_F",
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP Beard ==================================================
			"CUP_G_Beard_Shades_Black",
			"CUP_G_Beard_Shades_Blonde",
			"CUP_Beard_Black",
			"CUP_Beard_Blonde",
			"CUP_Beard_Brown",
		// CUP RUS ==================================================
			"CUP_RUS_Balaclava_blk",
			"CUP_RUS_Balaclava_emr",
			"CUP_RUS_Balaclava_grn",
			"CUP_RUS_Balaclava_rgr",
			"CUP_G_RUS_Balaclava_Ratnik",
			"CUP_G_RUS_Balaclava_Ratnik_v2",
			"CUP_RUS_Balaclava_tan",
		// CUP ESS ==================================================
			"CUP_G_ESS_BLK_Dark",
			"CUP_G_ESS_BLK_Ember",
			"CUP_G_ESS_BLK",
			"CUP_G_ESS_RGR_Dark",
			"CUP_G_ESS_RGR_Ember",
			"CUP_G_ESS_RGR",
			"CUP_G_ESS_CBR_Dark",
			"CUP_G_ESS_CBR_Ember",
			"CUP_G_ESS_CBR",
			"CUP_G_ESS_KHK_Dark",
			"CUP_G_ESS_KHK_Ember",
			"CUP_G_ESS_KHK",
			"CUP_G_ESS_BLK_Facewrap_Black",
			"CUP_G_ESS_RGR_Facewrap_Ranger",
			"CUP_G_ESS_RGR_Facewrap_Skull",
			"CUP_G_ESS_RGR_Facewrap_Tropical",
			"CUP_G_ESS_KHK_Facewrap_Tan",
			"CUP_G_ESS_BLK_Scarf_Blk",
			"CUP_G_ESS_BLK_Scarf_Grn",
			"CUP_G_ESS_KHK_Scarf_Tan",
			"CUP_G_ESS_BLK_Scarf_Face_Blk",
			"CUP_G_ESS_BLK_Scarf_Face_Grn",
			"CUP_G_ESS_KHK_Scarf_Face_Tan",
		// CUP PMC ==================================================
			"CUP_PMC_Facewrap_Black",
			"CUP_PMC_Facewrap_Ranger",
			"CUP_PMC_Facewrap_Skull",
			"CUP_PMC_Facewrap_Tropical",
			"CUP_PMC_Facewrap_Tan",
			"CUP_G_PMC_Facewrap_Black_Glasses_Dark_Headset",
			"CUP_G_PMC_Facewrap_Black_Glasses_Dark",
			"CUP_G_PMC_Facewrap_Black_Glasses_Ember",
			"CUP_G_PMC_Facewrap_Tropical_Glasses_Dark_Headset",
			"CUP_G_PMC_Facewrap_Tropical_Glasses_Dark",
			"CUP_G_PMC_Facewrap_Tropical_Glasses_Ember",
			"CUP_G_PMC_Facewrap_Tan_Glasses_Dark_Headset",
			"CUP_G_PMC_Facewrap_Tan_Glasses_Dark",
			"CUP_G_PMC_Facewrap_Tan_Glasses_Ember",
			"CUP_G_PMC_RadioHeadset",
			"CUP_G_PMC_RadioHeadset_Glasses",
			"CUP_G_PMC_RadioHeadset_Glasses_Dark",
			"CUP_G_PMC_RadioHeadset_Glasses_Ember",
		// CUP Scarf ==================================================
			"CUP_G_Scarf_Face_Blk",
			"CUP_G_Scarf_Face_Grn",
			"CUP_G_Scarf_Face_Tan",
			"CUP_G_Grn_Scarf_Shades",
			"CUP_G_Tan_Scarf_Shades",
		// CUP Oakleys ==================================================
			"CUP_G_Oakleys_Clr",
			"CUP_G_Oakleys_Drk",
			"CUP_G_Oakleys_Embr",
		// CUP FR ==================================================
			"CUP_FR_NeckScarf3",
			"CUP_FR_NeckScarf",
			"CUP_FR_NeckScarf2"
];

_items = [
	// ======================================================================
	// NVG
	// ======================================================================
		// Vanilla ================================================
			"NVGoggles_INDEP"				,
			"NVGoggles_OPFOR"				,
			"NVGoggles_tna_F"				,
			"O_NVGoggles_ghex_F"			,
			"O_NVGoggles_grn_F"				,
		// AGE ====================================================
			"AGE_ANPVS14_H",
			"AGE_ANPVS14_H_EP",
			"AGE_ANPVS14_H_Armband_O",
			"AGE_ANPVS14_H_Armband_Y",
			"AGE_Armband_O",
			"AGE_Armband_Y",
			"AGE_SPLAV_Gloves_H",
		// CUP ==================================================
			"CUP_NVG_PVS15_black",
			"CUP_NVG_PVS15_green",
			"CUP_NVG_PVS15_Hide",
			"CUP_NVG_PVS15_tan",
			"CUP_NVG_PVS7",
			"CUP_NVG_PVS7_Hide",
			"CUP_NVG_PVS14",
			"CUP_NVG_PVS14_Hide",
			"CUP_NVG_GPNVG_black",
			"CUP_NVG_GPNVG_green",
			"CUP_NVG_GPNVG_Hide",
			"CUP_NVG_GPNVG_tan",
			"CUP_NVG_HMNVS",
			"CUP_NVG_HMNVS_Hide",
	// ======================================================================
	// Binoculars
	// ======================================================================
		// "All" ==================================================
			// Vanilla ==================================
				"Binocular"					,
	// ======================================================================
	// Map
	// ======================================================================
		// Vanilla ================================================
			"ItemMap"						,
	// ======================================================================
	// Terminal
	// ======================================================================
		// "All" ==================================================
			// Vanilla ==================================
				"ItemGPS"					,
	// ======================================================================
	// Radio
	// ======================================================================
		// Vanilla ================================================
			"ItemRadio"						,
	// ======================================================================
	// Compass
	// ======================================================================
		// Vanilla ================================================
			"ItemCompass"					,
	// ======================================================================
	// Watch
	// ======================================================================
		// Vanilla ================================================
			"ItemWatch"						,
			"ChemicalDetector_01_watch_F"	,
	// ======================================================================
	// Other
	// ======================================================================
		// "All" ==================================================
			// Vanilla ==================================
				"MineDetector"				,
				"FirstAidKit"				,
		// "MED" ============================================================
			// Vanilla ==================================
				"Medikit"					,
		// "ING" ============================================================
			// Vanilla ==================================
			//	"ToolKit"					,
	// ======================================================================
	// Grenades
	// ======================================================================
		// "All" ==================================================
			// Vanilla ==================================
				"SmokeShell"				,
				"SmokeShellYellow"			,
				"SmokeShellGreen"			,
				"SmokeShellRed"				,
				"SmokeShellOrange"			,
				"SmokeShellPurple"			,
				"SmokeShellBlue"			,
				"O_IR_Grenade"				,
				"MiniGrenade"				,
				"HandGrenade"				,
				"Chemlight_yellow"			,
				"Chemlight_green"			,
				"Chemlight_red"				,
				"Chemlight_blue"			,
			// CUP ==================================================
				"CUP_HandGrenade_M67",
				"CUP_HandGrenade_RGD5",
				"CUP_HandGrenade_RGO",
				"CUP_HandGrenade_L109A1_HE",
				"CUP_HandGrenade_L109A2_HE",
	// ======================================================================
	// Mines
	// ======================================================================
		// "All" ==================================================
			// Vanilla ==================================
				"DemoCharge_Remote_Mag"		,
				"SatchelCharge_Remote_Mag"	,
			// CUP ==================================================
				"CUP_PipeBomb_M",
				"CUP_TimeBomb_M"
];

_handgunWeapon = [
	// ======================================================================
	// VANILLA
	// ======================================================================
		// Pistols ==============================================
			// .45 ACP ==============================
				"hgun_ACPC2_F"						,
				"hgun_Pistol_heavy_01_F"			,
				"hgun_Pistol_heavy_01_green_F"		,
				"hgun_Pistol_heavy_02_F"			,
			// 9 mm =================================
				"hgun_P07_blk_F"					,
				"hgun_P07_F"						,
				"hgun_P07_khk_F"					,
				"hgun_Pistol_01_F"					,
				"hgun_Rook40_F"						,
	// ======================================================================
	// AEW
	// ======================================================================
		"MYR_pistol_heavy_1_black",
		"MYR_pistol_heavy_1_black_sage",
		"MYR_pistol_heavy_1_green",
		"WAM_hgun_ACPC2_blk_F",
		"WAM_hgun_ACPC2_KDW_F",
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP pistols ==================================================
			"CUP_hgun_Browning_HP",
			"CUP_hgun_CZ75",
			"CUP_hgun_Compact",
			"CUP_hgun_Duty",
			"CUP_hgun_Phantom",
			"CUP_hgun_Deagle",
			"CUP_hgun_Glock17",
			"CUP_hgun_Glock17_tan",
			"CUP_hgun_Glock17_blk",
			"CUP_hgun_M17_Black",
			"CUP_hgun_M17_Coyote",
			"CUP_hgun_M17_Green",
			"CUP_hgun_Colt1911",
			"hgun_esd_01_F",
			"CUP_hgun_M9",
			"CUP_hgun_M9A1",
			"CUP_hgun_Mk23",
			"CUP_hgun_TaurusTracker455",
			"CUP_hgun_TT",
			"CUP_hgun_PMM",
			"CUP_hgun_Makarov",
			"CUP_hgun_PB6P9"
];

_secondaryWeapon = [
	// ======================================================================
	// Vanilla
	// ======================================================================
];

_primaryWeapon = [
	// ======================================================================
	//			Vanilla
	// ======================================================================
		// Machineguns ==========================================
			// .338 =================================
				"MMG_02_black_F"					,
			// 5.56 x 45 ============================
				"arifle_SPAR_02_blk_F"				,
				"arifle_SPAR_02_khk_F"				,
				"LMG_03_F"							,
			// 5.80 x 42 ============================
				"arifle_CTARS_blk_F"				,
				"arifle_CTARS_ghex_F"				,
				"arifle_CTARS_hex_F"				,
			// 6.50 x 39 ============================
				"arifle_MX_SW_Black_F"				,
				"arifle_MX_SW_khk_F"				,
				"LMG_Mk200_black_F"					,
			// 7.62 x 39 ============================
				"arifle_RPK12_F"					,
				"arifle_RPK12_lush_F"				,
				"LMG_Zafir_F"						,
			// 9.30 x 64 ============================
				"MMG_01_hex_F"						,
	// ======================================================================
	// AEW
	// ======================================================================
		"NAA_LMG_03_alpat_F",
		"MYR_arifle_MX_SW_blk_sage_F",
		"MYR_arifle_MX_SW_sage_F",
		"HEL_MX_SW_blk_F",
		"MYR_navid_black_F",
		"MYR_navid_sage_F",
		"NAA_MMG_02_alpat_F",
	// ======================================================================
	// SMA
	// ======================================================================
		// Machineguns ===================================================
			"sma_minimi_mk3_762tlb"	,
			"sma_minimi_mk3_762tlb_wdl"	,
			"sma_minimi_mk3_762tsb"	,
			"sma_minimi_mk3_762tsb_wdl"	,
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP L86 A2 ==================================================
			"CUP_arifle_L86A2",
		// CUP MG36 ==================================================
			"CUP_arifle_MG36",
			"CUP_arifle_MG36_camo",
			"CUP_arifle_MG36_hex",
			"CUP_arifle_MG36_wdl",
		// CUP RPK74 ==================================================
			"CUP_arifle_RPK74",
			"CUP_arifle_RPK74_45",
			"CUP_arifle_RPK74_45_top_rail",
			"CUP_arifle_RPK74_top_rail",
		// CUP RPK74M ==================================================
			"CUP_arifle_RPK74M",
			"CUP_arifle_RPK74M_railed",
			"CUP_arifle_RPK74M_top_rail",
		// CUP XM8 ==================================================
			"CUP_arifle_xm8_SAW",
		// CUP FNMAG ==================================================
			"CUP_lmg_FNMAG",
			"CUP_lmg_FNMAG_RIS",
			"CUP_lmg_FNMAG_RIS_modern",
		// CUP L110 A1 ==================================================
			"CUP_lmg_L110A1",
		// CUP L7 A2 ==================================================
			"CUP_lmg_L7A2",
			"CUP_lmg_L7A2_Flat",
		// CUP M240 ==================================================
			"CUP_lmg_M240",
			"CUP_lmg_M240_B",
			"CUP_lmg_M240_norail",
		// CUP M249 ==================================================
			"CUP_lmg_M249_E1",
			"CUP_lmg_M249_E2",
			"CUP_lmg_m249_para",
			"CUP_lmg_m249_pip1",
			"CUP_lmg_m249_pip2",
			"CUP_lmg_m249_pip3",
			"CUP_lmg_m249_pip4",
			"CUP_lmg_m249_SQuantoon",
		// CUP M60 ==================================================
			"CUP_lmg_M60",
		// CUP M60 E4 ==================================================
			"CUP_lmg_M60E4",
			"CUP_lmg_M60E4_desert",
			"CUP_lmg_M60E4_jungle",
			"CUP_lmg_M60E4_norail",
			"CUP_lmg_M60E4_norail_desert",
			"CUP_lmg_M60E4_norail_jungle",
			"CUP_lmg_M60E4_norail_wood",
			"CUP_lmg_M60E4_wood",
		// CUP MG3 ==================================================
			"CUP_lmg_MG3",
			"CUP_lmg_MG3_rail",
		// CUP minimi ==================================================
			"CUP_lmg_minimi",
			"CUP_lmg_minimi_railed",
			"CUP_lmg_minimipara",
		// CUP Mk48 ==================================================
			"CUP_lmg_Mk48",
			"CUP_lmg_Mk48_des",
			"CUP_lmg_Mk48_nohg",
			"CUP_lmg_Mk48_nohg_des",
			"CUP_lmg_Mk48_nohg_od",
			"CUP_lmg_Mk48_nohg_wdl",
			"CUP_lmg_Mk48_od",
			"CUP_lmg_Mk48_wdl",
		// CUP Pecheneg ==================================================
			"CUP_lmg_Pecheneg",
			"CUP_lmg_Pecheneg_B50_vfg",
			"CUP_lmg_Pecheneg_desert",
			"CUP_lmg_Pecheneg_top_rail",
			"CUP_lmg_Pecheneg_top_rail_B50_vfg",
			"CUP_lmg_Pecheneg_woodland",
		// CUP PKM ==================================================
			"CUP_lmg_PKM",
			"CUP_lmg_PKM_B50_vfg",
			"CUP_lmg_PKM_front_rail_B50_vfg",
			"CUP_lmg_PKM_top_rail",
			"CUP_lmg_PKM_top_rail_B50_vfg",
		// CUP PKMN ==================================================
			"CUP_lmg_PKMN",
		// CUP UK59 ==================================================
			"CUP_lmg_UK59"
];

_optics = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		// VANILA ASSAULT RIFLES ============================================
			"optic_aco",
			"optic_Aco",
			"optic_ACO_grn",
			"optic_ACO_grn_smg",
			"optic_aco_smg",
			"optic_Aco_smg",
			"optic_Arco",
			"optic_Arco_AK_arid_F",
			"optic_Arco_AK_blk_F",
			"optic_Arco_AK_lush_F",
			"optic_Arco_arid_F",
			"optic_Arco_blk_F",
			"optic_Arco_ghex_F",
			"optic_Arco_lush_F",
			"optic_ERCO_blk_F",
			"optic_ERCO_khk_F",
			"optic_Hamr",
			"optic_Hamr_khk_F",
			"optic_ico_01_black_f",
			"optic_ico_01_camo_f",
			"optic_ico_01_f",
			"optic_MRCO",
		// VANILA SNIPER RIFLES =============================================
		// VANILA PISTOLS ===================================================
			"optic_Holosight",
			"optic_Holosight_arid_F",
			"optic_Holosight_blk_F",
			"optic_Holosight_khk_F",
			"optic_Holosight_lush_F",
			"optic_Holosight_smg",
			"optic_Holosight_smg_blk_F",
			"optic_Holosight_smg_khk_F",
			"optic_MRD",
			"optic_MRD_black",
			"optic_Yorris",
	// ======================================================================
	// SMA
	// ======================================================================
		// SMG ==================================================
			"SMA_eotech552"										,
			"SMA_eotech552_kf"									,
			"SMA_eotech552_kf_wdl"								,
			"SMA_eotech"										,
			"SMA_eotech_G"										,
			"SMA_BARSKA"										,
			"SMA_CMORE"											,
			"SMA_CMOREGRN"										,
		// InfantryOptics =======================================
			"SMA_ELCAN_SPECTER"									,
			"SMA_ELCAN_SPECTER_RDS"								,
			"SMA_ELCAN_SPECTER_ARDRDS"							,
			"SMA_ELCAN_SPECTER_GREEN"							,
			"SMA_ELCAN_SPECTER_GREEN_RDS"						,
			"SMA_ELCAN_SPECTER_GREEN_ARDRDS"					,
			"SMA_eotech552_3XDOWN"								,
			"SMA_eotech552_3XUP"								,
			"SMA_eotech552_3XDOWN_wdl"							,
			"SMA_eotech552_3XUP_wdl"							,
			"SMA_eotechG33_3XDOWN"								,
			"SMA_eotechG33_3XUP"								,
			"SMA_eotechG33_grn_3XDOWN"							,
			"SMA_eotechG33_grn_3XUP"							,
			"SMA_MICRO_T2"										,
			"SMA_MICRO_T2_3XDOWN"								,
			"SMA_MICRO_T2_3XUP"									,
			"SMA_MICRO_T2_LM"									,
			"SMA_AIMPOINT"										,
			"SMA_AIMPOINT_GLARE"								,
			"sma_spitfire_01_black"								,
			"sma_spitfire_01_sc_black"							,
			"sma_spitfire_03_black"								,
			"sma_spitfire_03_sc_black"							,
			"sma_spitfire_03_rds_black"							,
			"sma_spitfire_03_rds_low_ard_black"					,
			"sma_spitfire_03_rds_low_black"						,
		// LostClassnames =======================================
			"SMA_ELCAN_SPECTER_GREEN3"		,
			"SMA_ELCAN_SPECTER_GREEN3_ARDRDS"		,
			"SMA_ELCAN_SPECTER_GREEN3_RDS"		,
			"SMA_ELCAN_SPECTER_GREEN5"		,
			"SMA_ELCAN_SPECTER_GREEN5_ARDRDS"		,
			"SMA_ELCAN_SPECTER_GREEN5_RDS"		,
			"SMA_ELCAN_SPECTER_GREEN6"		,
			"SMA_ELCAN_SPECTER_GREEN6_ARDRDS"		,
			"SMA_ELCAN_SPECTER_GREEN6_RDS"		,
			"SMA_ELCAN_SPECTER3"		,
			"SMA_ELCAN_SPECTER3_ARDRDS"		,
			"SMA_ELCAN_SPECTER3_RDS"		,
			"SMA_ELCAN_SPECTER5"		,
			"SMA_ELCAN_SPECTER5_ARDRDS"		,
			"SMA_ELCAN_SPECTER5_RDS"		,
			"SMA_ELCAN_SPECTER6"		,
			"SMA_ELCAN_SPECTER6_ARDRDS"		,
			"SMA_ELCAN_SPECTER6_RDS"		,
			"sma_spitfire_01_green"		,
			"sma_spitfire_01_red"		,
			"sma_spitfire_01_sc_closed"		,
			"sma_spitfire_01_sc_green"		,
			"sma_spitfire_01_sc_red"		,
			"sma_spitfire_03_green"		,
			"sma_spitfire_03_rds_green"		,
			"sma_spitfire_03_rds_low_ard_green"		,
			"sma_spitfire_03_rds_low_ard_red"		,
			"sma_spitfire_03_rds_low_green"		,
			"sma_spitfire_03_rds_low_red"		,
			"sma_spitfire_03_rds_red"		,
			"sma_spitfire_03_red"		,
			"sma_spitfire_03_sc_closed"		,
			"sma_spitfire_03_sc_green"		,
			"sma_spitfire_03_sc_red"		,
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP ASSAULT RIFLES ==================================================
			"CUP_optic_1p63",
			"CUP_optic_1P87_RIS",
			"CUP_optic_1P87_RIS_desert",
			"CUP_optic_1P87_RIS_woodland",
			"CUP_optic_AC11704_Black",
			"CUP_optic_AC11704_Coyote",
			"CUP_optic_AC11704_Jungle",
			"CUP_optic_AC11704_OD",
			"CUP_optic_ACOG",
			"CUP_optic_ACOG_Reflex_Desert",
			"CUP_optic_ACOG_Reflex_Wood",
			"CUP_optic_ACOG_TA01B_Black",
			"CUP_optic_ACOG_TA01B_Coyote",
			"CUP_optic_ACOG_TA01B_OD",
			"CUP_optic_ACOG_TA01B_RMR_Black",
			"CUP_optic_ACOG_TA01B_RMR_Coyote",
			"CUP_optic_ACOG_TA01B_RMR_OD",
			"CUP_optic_ACOG_TA01B_RMR_Tropic",
			"CUP_optic_ACOG_TA01B_Tropic",
			"CUP_optic_ACOG_TA01NSN_OD",
			"CUP_optic_ACOG_TA01NSN_RMR_Black",
			"CUP_optic_ACOG_TA01NSN_RMR_Coyote",
			"CUP_optic_ACOG_TA01NSN_RMR_OD",
			"CUP_optic_ACOG_TA01NSN_RMR_Tropic",
			"CUP_optic_ACOG_TA01NSN_Tropic",
			"CUP_optic_ACOG_TA31_KF",
			"CUP_optic_ACOG_TA31_KF_Desert",
			"CUP_optic_ACOG_TA31_KF_Wood",
			"CUP_optic_ACOG2",
			"CUP_optic_AIMM_COMPM2_BLK",
			"CUP_optic_AIMM_COMPM2_OD",
			"CUP_optic_AIMM_COMPM4_BLK",
			"CUP_optic_AIMM_M68_BLK",
			"CUP_optic_AIMM_M68_OD",
			"CUP_optic_AIMM_MARS_BLK",
			"CUP_optic_AIMM_MARS_OD",
			"CUP_optic_AIMM_MICROT1_BLK",
			"CUP_optic_AIMM_MICROT1_OD",
			"CUP_optic_AIMM_ZDDOT_BLK",
			"CUP_optic_Aimpoint_5000",
			"CUP_optic_AN_PVS_4_M16",
			"CUP_optic_CompM2_Black",
			"CUP_optic_CompM2_Coyote",
			"CUP_optic_CompM2_Desert",
			"CUP_optic_CompM2_low",
			"CUP_optic_CompM2_low_coyote",
			"CUP_optic_CompM2_low_OD",
			"CUP_optic_CompM2_OD",
			"CUP_optic_CompM2_Woodland",
			"CUP_optic_CompM2_Woodland2",
			"CUP_optic_CompM4",
			"CUP_optic_ekp_8_02",
			"CUP_optic_Elcan",
			"CUP_optic_Elcan_Coyote",
			"CUP_optic_Elcan_OD",
			"CUP_optic_Elcan_reflex",
			"CUP_optic_Elcan_reflex_Coyote",
			"CUP_optic_Elcan_reflex_OD",
			"CUP_optic_Elcan_SpecterDR",
			"CUP_optic_Elcan_SpecterDR_black",
			"CUP_optic_Elcan_SpecterDR_coyote",
			"CUP_optic_Elcan_SpecterDR_KF",
			"CUP_optic_Elcan_SpecterDR_KF_black",
			"CUP_optic_Elcan_SpecterDR_KF_coyote",
			"CUP_optic_Elcan_SpecterDR_KF_od",
			"CUP_optic_Elcan_SpecterDR_KF_RMR",
			"CUP_optic_Elcan_SpecterDR_KF_RMR_black",
			"CUP_optic_Elcan_SpecterDR_KF_RMR_coyote",
			"CUP_optic_Elcan_SpecterDR_KF_RMR_od",
			"CUP_optic_Elcan_SpecterDR_od",
			"CUP_optic_Elcan_SpecterDR_RMR",
			"CUP_optic_Elcan_SpecterDR_RMR_black",
			"CUP_optic_Elcan_SpecterDR_RMR_coyote",
			"CUP_optic_Elcan_SpecterDR_RMR_od",
			"CUP_optic_ElcanM145",
			"CUP_optic_Eotech533",
			"CUP_optic_Eotech533Grey",
			"CUP_optic_Eotech553_Black",
			"CUP_optic_Eotech553_Coyote",
			"CUP_optic_Eotech553_OD",
			"CUP_optic_G33_HWS_BLK",
			"CUP_optic_G33_HWS_COYOTE",
			"CUP_optic_G33_HWS_OD",
			"CUP_optic_G36DualOptics",
			"CUP_optic_G36DualOptics_3D",
			"CUP_optic_G36DualOptics_desert",
			"CUP_optic_G36DualOptics_desert_3D",
			"CUP_optic_G36DualOptics_wood",
			"CUP_optic_G36DualOptics_wood_3D",
			"CUP_optic_G36Optics",
			"CUP_optic_G36Optics_3D",
			"CUP_optic_G36Optics_desert",
			"CUP_optic_G36Optics_desert_3D",
			"CUP_optic_G36Optics_Holo",
			"CUP_optic_G36Optics_Holo_3D",
			"CUP_optic_G36Optics_Holo_desert",
			"CUP_optic_G36Optics_Holo_desert_3D",
			"CUP_optic_G36Optics_Holo_wood",
			"CUP_optic_G36Optics_Holo_wood_3D",
			"CUP_optic_G36Optics_RDS",
			"CUP_optic_G36Optics_RDS_3D",
			"CUP_optic_G36Optics_RDS_desert",
			"CUP_optic_G36Optics_RDS_desert_3D",
			"CUP_optic_G36Optics_RDS_wood",
			"CUP_optic_G36Optics_RDS_wood_3D",
			"CUP_optic_G36Optics_wood",
			"CUP_optic_G36Optics_wood_3D",
			"CUP_optic_G36Optics15x",
			"CUP_optic_G36Optics15x_3D",
			"CUP_optic_G36Optics15x_desert",
			"CUP_optic_G36Optics15x_desert_3D",
			"CUP_optic_G36Optics15x_wood",
			"CUP_optic_G36Optics15x_wood_3D",
			"CUP_optic_HensoldtZO",
			"CUP_optic_HensoldtZO_coyote",
			"CUP_optic_HensoldtZO_desert",
			"CUP_optic_HensoldtZO_hex",
			"CUP_optic_HensoldtZO_low",
			"CUP_optic_HensoldtZO_low_coyote",
			"CUP_optic_HensoldtZO_low_desert",
			"CUP_optic_HensoldtZO_low_hex",
			"CUP_optic_HensoldtZO_low_od",
			"CUP_optic_HensoldtZO_low_RDS",
			"CUP_optic_HensoldtZO_low_RDS_coyote",
			"CUP_optic_HensoldtZO_low_RDS_desert",
			"CUP_optic_HensoldtZO_low_RDS_hex",
			"CUP_optic_HensoldtZO_low_RDS_od",
			"CUP_optic_HensoldtZO_od",
			"CUP_optic_HensoldtZO_RDS",
			"CUP_optic_HensoldtZO_RDS_coyote",
			"CUP_optic_HensoldtZO_RDS_desert",
			"CUP_optic_HensoldtZO_RDS_hex",
			"CUP_optic_HensoldtZO_RDS_od",
			"CUP_optic_HoloBlack",
			"CUP_optic_HoloDesert",
			"CUP_optic_HoloWdl",
			"CUP_optic_Kobra",
			"CUP_optic_LeupoldMk4_CQ_T",
			"CUP_optic_MARS",
			"CUP_optic_MARS_OD",
			"CUP_optic_MEPRO",
			"CUP_optic_MEPRO_moa_clear",
			"CUP_optic_MEPRO_openx_orange",
			"CUP_optic_MEPRO_tri_clear",
			"CUP_optic_MicroT1",
			"CUP_optic_MicroT1_coyote",
			"CUP_optic_MicroT1_low",
			"CUP_optic_MicroT1_low_coyote",
			"CUP_optic_MicroT1_low_OD",
			"CUP_optic_MicroT1_OD",
			"CUP_optic_MRad",
			"CUP_optic_NSPU",
			"CUP_optic_PechenegScope",
			"CUP_optic_PEM",
			"CUP_optic_PSO_1",
			"CUP_optic_PSO_1_1",
			"CUP_optic_PSO_1_1_open",
			"CUP_optic_PSO_1_AK",
			"CUP_optic_PSO_1_AK_open",
			"CUP_optic_PSO_1_open",
			"CUP_optic_RCO",
			"CUP_optic_RCO_desert",
			"CUP_optic_Remington",
			"CUP_optic_SB_11_4x20_PM",
			"CUP_optic_SB_11_4x20_PM_od",
			"CUP_optic_SUSAT",
			"CUP_optic_TrijiconRx01_black",
			"CUP_optic_TrijiconRx01_desert",
			"CUP_optic_TrijiconRx01_kf_black",
			"CUP_optic_TrijiconRx01_kf_desert",
			"CUP_optic_TrijiconRx01_kf_od",
			"CUP_optic_TrijiconRx01_od",
			"CUP_optic_VortexRazor_UH1_Black",
			"CUP_optic_VortexRazor_UH1_Coyote",
			"CUP_optic_VortexRazor_UH1_Khaki",
			"CUP_optic_VortexRazor_UH1_OD",
			"CUP_optic_ZDDot",
			"CUP_optic_ZeissZPoint",
			"CUP_optic_ZeissZPoint_hex",
			"CUP_optic_ZeissZPoint_wood"
];

_muzzles = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		// VANILA muzzle for pistols ========================================
			"muzzle_snds_acp",
			"muzzle_snds_L",
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP muzzle for pistols ==================================================
			"CUP_muzzle_snds_mk23",
			"CUP_muzzle_snds_M9"
];

_pointers = [
	// ======================================================================
	// Vanilla
	// ======================================================================
		// VANILA acc for pistols ===============================
			"acc_flashlight_pistol"								,
		// VANILA acc for rifles ================================
			"acc_flashlight"									,
			"acc_flashlight_smg_01"								,
			"acc_pointer_IR"									,
	// ======================================================================
	// SMA
	// ======================================================================
		// Infantry Attachments =================================
			"SMA_ANPEQ15_BLK"									,
			"SMA_ANPEQ15_TOP_BLK"								,
			"SMA_ANPEQ15_TOP_BLK_ACR"							,
			"SMA_ANPEQ15_TOP_BLK_M4"							,
			"SMA_ANPEQ15_TOP_BLK_MK18"							,
			"SMA_ANPEQ15_TOP_BLK_SCAR"							,
			"SMA_RAILGUARD_BLK_HK"								,
			"SMA_RAILGUARD_OD_HK"								,
			"SMA_RAILGUARD_TAN_HK"								,
			"SMA_SFFL_BLK"										,
			"SMA_SFPEQ_ACRTOP_BLK"								,
			"SMA_SFPEQ_AUGCQC_BLK"								,
			"SMA_SFPEQ_HKTOP_BLK"								,
			"SMA_SFPEQ_M4TOP_BLK"								,
			"SMA_SFPEQ_MK18TOP_BLK"								,
			"SMA_SFPEQ_SCARTOP_BLK"								,
	// ======================================================================
	//			CUP
	// ======================================================================
		// CUP acc for pistols ==================================================
			"CUP_acc_MLPLS_Laser",
			"CUP_acc_Glock17_Flashlight",
			"CUP_acc_CZ_M3X",
		// CUP acc for rifles ==================================================
			"CUP_acc_ANPEQ_15",
			"CUP_acc_ANPEQ_15_Black",
			"CUP_acc_ANPEQ_15_Black_Top",
			"CUP_acc_ANPEQ_15_Flashlight_Black_F",
			"CUP_acc_ANPEQ_15_Flashlight_Black_L",
			"CUP_acc_ANPEQ_15_Flashlight_OD_F",
			"CUP_acc_ANPEQ_15_Flashlight_OD_L",
			"CUP_acc_ANPEQ_15_Flashlight_Tan_F",
			"CUP_acc_ANPEQ_15_Flashlight_Tan_L",
			"CUP_acc_ANPEQ_15_OD",
			"CUP_acc_ANPEQ_15_OD_Top",
			"CUP_acc_ANPEQ_15_Tan_Top",
			"CUP_acc_ANPEQ_15_Top_Flashlight_Black_F",
			"CUP_acc_ANPEQ_15_Top_Flashlight_Black_L",
			"CUP_acc_ANPEQ_15_Top_Flashlight_OD_F",
			"CUP_acc_ANPEQ_15_Top_Flashlight_OD_L",
			"CUP_acc_ANPEQ_15_Top_Flashlight_Tan_F",
			"CUP_acc_ANPEQ_15_Top_Flashlight_Tan_L",
			"CUP_acc_ANPEQ_2",
			"CUP_acc_ANPEQ_2_Black_Top",
			"CUP_acc_ANPEQ_2_camo",
			"CUP_acc_ANPEQ_2_Coyote_Top",
			"CUP_acc_ANPEQ_2_desert",
			"CUP_acc_ANPEQ_2_Flashlight_Black_F",
			"CUP_acc_ANPEQ_2_Flashlight_Black_L",
			"CUP_acc_ANPEQ_2_Flashlight_Coyote_F",
			"CUP_acc_ANPEQ_2_Flashlight_Coyote_L",
			"CUP_acc_ANPEQ_2_Flashlight_OD_F",
			"CUP_acc_ANPEQ_2_Flashlight_OD_L",
			"CUP_acc_ANPEQ_2_grey",
			"CUP_acc_ANPEQ_2_OD_Top",
			"CUP_acc_CZ_M3X_L",
			"CUP_acc_Flashlight",
			"CUP_acc_Flashlight_desert",
			"CUP_acc_Flashlight_wdl",
			"CUP_acc_LLM",
			"CUP_acc_LLM_black",
			"CUP_acc_LLM_Flashlight",
			"CUP_acc_LLM_od",
			"CUP_acc_LLM01_coyote_L",
			"CUP_acc_LLM01_desert_L",
			"CUP_acc_LLM01_hex_L",
			"CUP_acc_LLM01_L",
			"CUP_acc_LLM01_od_L",
			"CUP_acc_sffh",
			"CUP_acc_XM8_light_module",
			"CUP_SVD_camo_g",
			"CUP_SVD_camo_d"
];

_bipods = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		"bipod_01_F_blk",
		"bipod_01_F_khk",
		"bipod_01_F_mtp",
		"bipod_02_F_arid",
		"bipod_02_F_blk",
		"bipod_02_F_hex",
		"bipod_02_F_lush",
		"bipod_02_F_tan",
		"bipod_03_F_blk",
		"bipod_03_F_oli",
	// ======================================================================
	// SMA
	// ======================================================================
		"SMA_Gripod_01"					,
	// ======================================================================
	//			CUP
	// ======================================================================
		"CUP_bipod_FNFAL",
		"CUP_bipod_G3",
		"CUP_Bipod_G36",
		"CUP_Bipod_G36_desert",
		"CUP_Bipod_G36_wood",
		"CUP_bipod_G3SG1",
		"CUP_bipod_Harris_1A2_L",
		"CUP_bipod_Harris_1A2_L_BLK",
		"CUP_bipod_VLTOR_Modpod",
		"CUP_bipod_VLTOR_Modpod_black",
		"CUP_bipod_VLTOR_Modpod_od"
];

_exclMag = [
	// ======================================================================
	// VANILLA
	// ======================================================================
		// Balls ================================================
			"100rnd_65x39_caseless_mag"							,
			"100rnd_65x39_caseless_mag_tracer"					,
			"150rnd_556x45_drum_sand_mag_f"						,
			"150rnd_556x45_drum_sand_mag_tracer_f"				,
			"30rnd_556x45_stanag"								,
			"30rnd_556x45_stanag_green"							,
			"30rnd_556x45_stanag_red"							,
			"30rnd_556x45_stanag_sand"							,
			"30rnd_556x45_stanag_sand_green"					,
			"30rnd_556x45_stanag_sand_red"						,
			"30rnd_556x45_stanag_sand_tracer_green"				,
			"30rnd_556x45_stanag_sand_tracer_red"				,
			"30rnd_556x45_stanag_sand_tracer_yellow"			,
			"30rnd_556x45_stanag_tracer_green"					,
			"30rnd_556x45_stanag_tracer_red"					,
			"30rnd_556x45_stanag_tracer_yellow"					,
			"30rnd_580x42_mag_f"								,
			"30rnd_580x42_mag_tracer_f"							,
			"30rnd_65x39_caseless_black_mag"					,
			"30rnd_65x39_caseless_black_mag_tracer"				,
			"30rnd_65x39_caseless_khaki_mag"					,
			"30rnd_65x39_caseless_khaki_mag_tracer"				,
			"30rnd_65x39_caseless_mag"							,
			"30rnd_65x39_caseless_mag_tracer"					,
			"30rnd_762x39_ak12_arid_mag_f"						,
			"30rnd_762x39_ak12_arid_mag_tracer_f"				,
			"30rnd_762x39_ak12_lush_mag_f"						,
			"30rnd_762x39_ak12_lush_mag_tracer_f"				,
			"30rnd_762x39_ak12_mag_f"							,
			"30rnd_762x39_ak12_mag_tracer_f"					,
			"30rnd_762x39_mag_f"								,
			"30rnd_762x39_mag_green_f"							,
			"30rnd_762x39_mag_tracer_f"							,
			"30rnd_762x39_mag_tracer_green_f"					,
			"75rnd_762x39_ak12_arid_mag_f"						,
			"75rnd_762x39_ak12_arid_mag_tracer_f"				,
		// Underbarrel ==========================================
			"10rnd_50bw_mag_f"									,
			"6rnd_12gauge_slug"									,
		// Mines ================================================
			"APERSBoundingMine_Range_Mag"						,
			"APERSMine_Range_Mag"								,
			"APERSMineDispenser_Mag"							,
			"APERSTripMine_Wire_Mag"							,
			"ATMine_Range_Mag"									,
			"ClaymoreDirectionalMine_Remote_Mag"				,
			"IEDLandSmall_Remote_Mag"							,
			"IEDUrbanSmall_Remote_Mag"							,
			"SLAMDirectionalMine_Wire_Mag"						,
			"TrainingMine_Mag"									,
	// ======================================================================
	// SMA
	// ======================================================================
		// "M_CommonMagazines"	
			"SMA_30Rnd_762x35_BLK_EPR"	,
			"SMA_30Rnd_68x43_SPC_FMJ"	,
			"SMA_30Rnd_556x45_M855A1"	,
			"SMA_20Rnd_762x51mm_M80A1_EPR"	,
			"SMA_30Rnd_762x39_7n23_AP_Red"	,
			"SMA_30Rnd_762x35_SS"	,
			"SMA_30Rnd_68x43_SPC_FMJ_Tracer"	,
			"SMA_30Rnd_68x43_SPC_FMJ_IR"	,
			"SMA_30Rnd_68x43_sub"	,
			"SMA_30Rnd_68x43_sub_Tracer"	,
			"SMA_30Rnd_68x43_sub_IR"	,
			"SMA_30Rnd_556x45_M855A1_Tracer"	,
			"SMA_20Rnd_762x51mm_M80A1_EPR_Tracer"	,
			"SMA_20Rnd_762x51mm_M80A1_EPR_IR"	,
			"SMA_20Rnd_762x51mm_Lapua_FMJ_Subsonic"	,
			"SMA_20Rnd_762x51mm_Lapua_FMJ_Subsonic_Tracer"	,
			"SMA_20Rnd_762x51mm_Lapua_FMJ_Subsonic_IR"	,
		// "M_SniperMagazines"	
			"SMA_20Rnd_762x51mm_Mk316_Mod_0_Special_Long_Range"	,
			"SMA_20Rnd_762x51mm_Mk316_Mod_0_Special_Long_Range_Tracer"	,
			"SMA_20Rnd_762x51mm_Mk316_Mod_0_Special_Long_Range_IR"	,
			"SMA_30Rnd_68x43_BT"	,
			"SMA_30Rnd_68x43_BT_Tracer"	,
			"SMA_30Rnd_68x43_BT_IR"	,
			"SMA_30Rnd_556x45_Mk318"	,
			"SMA_30Rnd_556x45_Mk318_Tracer"	,
			"SMA_30Rnd_556x45_Mk318_IR"	,
			"SMA_30Rnd_556x45_Mk262"	,
			"SMA_30Rnd_556x45_Mk262_Tracer"	,
			"SMA_30Rnd_556x45_Mk262_IR"	,
	// ======================================================================
	//			CUP
	// ======================================================================
		"CUP_12Rnd_B_Saiga12_HE",
		"CUP_1Rnd_12Gauge_HE",
		"CUP_20Rnd_B_AA12_HE",
		"CUP_5Rnd_B_Saiga12_HE",
		"CUP_6Rnd_12Gauge_HE",
		"CUP_8Rnd_12Gauge_HE",
		"CUP_8Rnd_12Gauge_HE",
		"CUP_IED_V1_M",
		"CUP_IED_V2_M",
		"CUP_IED_V3_M",
		"CUP_IED_V4_M",
		"CUP_Mine_M",
		"CUP_MineE_M"
];

_allowedRockets = [
	// ======================================================================
	//			VANILA
	// ======================================================================
		"MRAWS_HE_F",
		"MRAWS_HEAT_F",
		"MRAWS_HEAT55_F",
		"NLAW_F",
		"RPG32_F",
		"RPG32_HE_F",
		"RPG7_F",
		"SPG9_HE",
		"SPG9_HEAT",
		"Titan_AA",
		"Titan_AP",
		"Titan_AT",
		"Vorona_HE",
		"Vorona_HEAT",
	// ======================================================================
	//			CUP
	// ======================================================================
		"CUP_AT13_M",
		"CUP_Dragon_EP1_M",
		"CUP_Igla_M",
		"CUP_Javelin_M",
		"CUP_M136_M",
		"CUP_M72A6_M",
		"CUP_MAAWS_HEAT_M",
		"CUP_MAAWS_HEAT_M",
		"CUP_MAAWS_HEDP_M",
		"CUP_NLAW_M",
		"CUP_OG7_M",
		"CUP_PG7V_M",
		"CUP_PG7VL_M",
		"CUP_PG7VM_M",
		"CUP_PG7VR_M",
		"CUP_RPG18_M",
		"CUP_SMAW_HEAA_M",
		"CUP_SMAW_HEDP_M",
		"CUP_SMAW_NE_M",
		"CUP_SMAW_Spotting",
		"CUP_Stinger_M",
		"CUP_Strela_2_M",
		"CUP_TBG7V_M"
];

_exclTypes = [];

_magazins = [];

{
    if (getNumber (_x >> "scope") == 2 || getNumber (_x >> "scopeArsenal") == 2) then {
        private _nameSound = getText (_x >> "nameSound");
        if !(_nameSound in _exclTypes) then {
            _magazins pushBack (configname _x);
        } else {
            if ((configname _x) in _allowedRockets) then {
                _magazins pushBack (configname _x);
            };
        };
    };
} forEach ("true" configclasses (configfile >> "CfgMagazines"));

_exclMagTMP = _exclMag apply {configName (configFile >> "CfgMagazines" >> _x)}; // Делаем правильные имена
_exclMag = _exclMagTMP; // Суем правильные имена обратно

_magazines = _magazins - _exclMag;